### ISSUE TITLE
Feature request: preview of apperance for Windows Classic theme

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#10]
Hello! This is a great tool! 

But Win32UI tab does not have a preview. Is it possible to add a preview for this set of customizations?

Some people still use Windows Classic, and some apps just do not use theming at all, defaulting to Windows Classic (for instance, CPU-Z and Winevdm).

**Comment by Abdelrhman-AK** [comment]
I'll add it in the next versions, thanks for your feedback!
