### ISSUE TITLE
Windows 3.1 schemes possibly should have "flat menus" attribute

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#100]
Currently:
![изображение](https://user-images.githubusercontent.com/1271736/222972140-ffa3a536-b116-454c-9e95-e3da6a8c5e4c.png)

Flat menus:
![изображение](https://user-images.githubusercontent.com/1271736/222972197-107b7d30-1de5-48bd-a6b2-b2135342c374.png)

For two reasons: first, its menus were indeed, flat; second, the menubar selection was solid, not 3D.

**Comment by Abdelrhman-AK** [comment]
I'll make these scemes have a flat mode
