### ISSUE TITLE
Pressing "Quick apply" button in Window Metrics dialog makes WinPalletter to hang

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#102]
If I press the "Quick apply" button in Windows Metrics dialog, with or without changes, WinPalletter is getting hang indefinitely, the changes made are applied to other apps, but WinPalletter process needs termination and restart.

**Comment by Abdelrhman-AK** [comment]
- Is this in 1.0.7.2 or in previous versions too?
- Is "Apply" button in main form have the same response or not?
- Try to restart your Windows and open WinPaletter alone and try again.

**Comment by Anixx** [comment]
I cannot reproduce this issue now, after Windows restart. Keep watching.

**Comment by Abdelrhman-AK** [comment]
I have tried to make applying theme in a separate thread since last month. It worked great except for UI errors.
I'll work on it again and make applying theme in a separate thread instead of a separate process.
