### ISSUE TITLE
Windows metrics previews

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#104]
I suggest to show Window Metrics previews either in Windows Classic theme or in the currently applied theme.

This is so one can see visual impact of the options "Button width" and "Border".

**Comment by Abdelrhman-AK** [comment]
It is already implemented. Here you are an example:
![0](https://user-images.githubusercontent.com/59510211/222978576-7816ccf6-7b1a-469a-baaf-cf4000f8400e.png)
![1](https://user-images.githubusercontent.com/59510211/222978582-67e29559-0abf-41d6-8da4-19ee11284052.png)

**Comment by Anixx** [comment]
Well, I see it this way:

![изображение](https://user-images.githubusercontent.com/1271736/222979881-5d0b0938-397b-497f-8bfa-3147e2b932ce.png)

Even when the Windows Classic theme is enabled (as you can see from the window borders).

**Comment by Anixx** [comment]
Did not notice the switch

**Comment by Anixx** [comment]
But window border width is still not visible on the previews, neither classic, nor aero.

**Comment by Abdelrhman-AK** [comment]
![Untitled](https://user-images.githubusercontent.com/59510211/222981862-2d7ca624-dd04-45eb-87c5-34adbebcded2.png)

I see that they are equal here. If it is not in yours, show me a screenshot to know where is the bug.

**Comment by Anixx** [comment]
The Windows Metrics previews simply do not show the window border thickness.

**Comment by Abdelrhman-AK** [comment]
![Untitled](https://user-images.githubusercontent.com/59510211/222983001-4abfbcba-5f57-4d8e-8d6c-7033ceb88979.png)

I didn't get your point. It is previewed correctly here in the screenshot

**Comment by Anixx** [comment]
In Classic Colors, yes, the window borders are visible, in Window Metrics dialog, no, regardless of theme.

**Comment by Abdelrhman-AK** [comment]
![Untitled](https://user-images.githubusercontent.com/59510211/222983290-ddd6abb8-04eb-480f-a25c-1365afd3fa03.png)
