### ISSUE TITLE
Add some customizations from Explorer Patcher?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#105]
Explorer Patcher includes some customization options which are basically registry values. I suggest adding some of them.
This is the complete list of the options: https://github.com/valinet/ExplorerPatcher/blob/master/ExplorerPatcher/settings.reg
But I want to highlight some.

Particularly:

[-HKEY_CURRENT_USER\Software\Classes\CLSID\{1eeb5b5a-06fb-4732-96b3-975c0194eb39}\InprocServer32]
;d Enable SysListView32 for Explorer views *
@=""

This makes the icon list in folders to use SysListView32 control, as in Windows 95-2003 (or Vista, not sure), instead of IconView.
This makes the table captions more compact, allows to re-arrange icons and when using Classic theme makes icon selection Windows 95-XP style instead of rectangles.

[-HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
;d Disable the Windows 11 context menu *
@=""

This disables the Windows 11 context menus, restoring the Windows 10 ones.

[-HKEY_CURRENT_USER\Software\Classes\CLSID\{056440FD-8568-48e7-A632-72157243B55B}\InprocServer32]
;d Disable navigation bar **
@=""

This disables Navigation Bar in File Explorer.

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
;z 4 Window switcher (Alt+Tab) style *
;x 0 Windows 11 (default)
;x 1 Windows NT
"AltTabSettings"=dword:00000000

This selects the Windows Switcher (Alt+Tab) style. See also here: https://winaero.com/enable-classic-alttab-dialog-in-windows-11/

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MultitaskingView\AltTabViewHost]
;c 19 Opacity
;x 100 Opaque
;x 98 98 %
;x 96 96 %
;x 95 95 % (default)
;x 94 94 %
;x 92 92 %
;x 90 90 %
;x 85 85 %
;x 80 80 %
;x 75 75 %
;x 70 70 %
;x 65 65 %
;x 60 60 %
;x 55 55 %
;x 50 50 %
;x 45 45 %
;x 40 40 %
;x 35 35 %
;x 30 30 %
"Grid_backgroundPercent"=dword:0000005F

Opacity of Alt+Tab switcher

**Comment by Abdelrhman-AK** [comment]
Currently I'm doing a preview sync with Windows 11 as requested in #28

![0](https://user-images.githubusercontent.com/59510211/222980127-00e225f3-6129-4fb6-9251-5a47089a514a.png)

After next update, I'll work on this.

**Comment by Anixx** [comment]
The keys above are not directly related to EP. Tese registry keys work just as well without EP at all. EP only provides user interface to change them.

**Comment by Abdelrhman-AK** [comment]
> The keys above are not directly related to EP. Tese registry keys work just as well without EP at all. EP only provides user interface to change them.

I didn't know about this before. I thought modifying them requires EP.
I'll work on these.
