### ISSUE TITLE
In Windows Metric Classic preview, the scrollbars have wrong size of arrows

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#107]
Here is what I see under "classic preview" in scrollbar size:
![изображение](https://user-images.githubusercontent.com/1271736/222980289-c2cb810a-ac90-4be3-b1cf-ccde9f5c890b.png)

Here is what I see when the "classic preview" is off:

![изображение](https://user-images.githubusercontent.com/1271736/222980336-83fa5751-23db-4e8e-906e-375aa868c6c6.png)

In the first case, the scrollbar arrows have wrong size and positioning.

In the second case, the scrollbars are correct, but represen Classic theme while one should expect Aero (because theClassic preview is switched off).

**Comment by Anixx** [comment]
I think, the color in the first case is also a bit wrong.

**Comment by Abdelrhman-AK** [comment]
- The second one uses the scrollbar of system directly, but the first one is the control I made for classic colors and copied it to Metrics & Fonts (Redrawn from init and not using system elements)
- When you set a modern theme, The second one will have the right look.
- I'll fix the layout and size of the first one.
- Which color in the first one is wrong?

**Comment by Anixx** [comment]
Possibly the wrong color is an optical illusion.
