### ISSUE TITLE
New Feature\Enhancement : Font Customization Options

### ISSUE THREAD

**Issue by Bamajon1974** [Abdelrhman-AK/WinPaletter#111]
Are there plans to implement font customization options in future versions of WinPaletter? 

For example, the ability to change font, font size, and font bold/italic/underline properties of title bars, menu bars, message boxes, secondary titles, icons and status bar? 

Or implement the same features as (Advanced) System Font Changer from WinTools.info. 

Thanks!

**Comment by Abdelrhman-AK** [comment]
It is already implemented in `Metrics And Fonts`

![0](https://user-images.githubusercontent.com/59510211/224504766-684ee013-a82f-47a1-b373-5370ea9bd350.png)

![1](https://user-images.githubusercontent.com/59510211/224504775-4c93264c-780b-4b41-b78b-af344c709fb3.png)

**Comment by Bamajon1974** [comment]
Oh wow, I didn't even notice you added the ability to customize fonts! Now I can eliminate another redundant software in System Font Changer. Thank you for the prompt response!

**Comment by Abdelrhman-AK** [comment]
You're welcome!
