### ISSUE TITLE
New Feature\Enhancement: PDB files? 

### ISSUE THREAD

**Issue by Bamajon1974** [Abdelrhman-AK/WinPaletter#112]
What are the PDB files in the releases section used for? Are they needed for WinPaletter to operate correctly? 

Thanks!

**Comment by Abdelrhman-AK** [comment]
It is used for debugging. You can ignore it.
You can basically use `WinPaletter.exe` only

**Comment by Bamajon1974** [comment]
Understood. Thank you for the prompt response.
