### ISSUE TITLE
The arrows and arrow buttons on scrollbars are still of wrong size here

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#113]
![изображение](https://user-images.githubusercontent.com/1271736/224514853-962654ef-5cdf-4698-90b2-7a6df7c2cc06.png)

Here the size is correct:
![изображение](https://user-images.githubusercontent.com/1271736/224514884-d69dd945-4421-4b8c-a5b9-4cd125246ee2.png)

**Comment by Abdelrhman-AK** [comment]
I forgot to adjust buttons heights.
But for the arrow it self, I tried to adjust it as much as I can. Marlett font is boring in adjusting its location, I'll try again.
