### ISSUE TITLE
The registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#114]
When using Windows Classic theme, the colors from this key get applied when pressing Ctrl+Alt-Del or logging off then logging in back.

Since this is detrimental and confusing, we usually delete this key altogether.

But it may be useful in other circumstances (about which I do not know). Since the key has effect and can be customized, this may be included in WinPaletter.

**Comment by Abdelrhman-AK** [comment]
I can add an option in Settings, if it is checked, classic colors will write to all users `HKEY_LOCAL_MACHINE\........\Themes\DefaultColors`

**Comment by Anixx** [comment]
Good idea, and possibly an option to erase it.

**Comment by OrthodoxWindows** [comment]
This registry key exists to apply system colors to the login screen.
It is divided into two sections: _DefaultColors\Standard_ and _DefaultColors\HighContrast_
The first is used for "normal" themes and the second for high contrast themes. The difference is that when changing a high contrast theme, the _DefaultColors\HighContrast_ key takes into account the color change. Whereas for _DefaultColors\Standard_, the color change is not taken into account. Adding this feature to actually a good idea.

Deleting the _DefaultColors\Standard_ key does not cause a problem. However, deleting _DefaultColors\HighContrast_ results in the disappearance of the high contrast theme when reconnecting (it may be possible to fix this, it can be interesting, in particular to obtain a logon screen without the high contrast on a theme high contrast).

**Comment by Abdelrhman-AK** [comment]
- In the next update, colors can be written to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors\Standard` by user's choice from Settings (Not `DefaultColors\HighContrast`)

- Writing to `HKEY_USERS\.DEFAULT\Control Panel\Colors` also made logonui have the same colors. (Tested on Windows XP and 7)

![Screenshot 2023-03-16 125902](https://user-images.githubusercontent.com/59510211/225599416-11124e52-cce8-4034-9287-35eb17c5a7f3.png)

**Comment by Anixx** [comment]
What's the point of erasing HKEY_USERS\.DEFAULT\Control Panel\Colors? I do not see any use case for this.

For the both keys possibly should be option "don't touch".

**Comment by Anixx** [comment]
HKEY_USERS.DEFAULT\Control Panel\Colors

* Overwrite
* Don't change

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors\Standard

* Overwrite
* Delete the key / erase
* Don't change

**Comment by OrthodoxWindows** [comment]
I agree with @anixx, except on the Delete the key / erase option. I'm afraid this will make it impossible to go back, I prefer a "Rename the key" option.

**Comment by Abdelrhman-AK** [comment]
> I agree with @Anixx, except on the Delete the key / erase option. I'm afraid this will make it impossible to go back, I prefer a "Rename the key" option.

Actually erasing them didn't cause an issue with me

**Comment by Abdelrhman-AK** [comment]
### So finally, can the layout be like this?

HKEY_USERS.DEFAULT\Control Panel\Colors

* Overwrite
* Don't change

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors\Standard

* Overwrite
* Restore Defaults
* Don't change

**Comment by Anixx** [comment]
The second one should include the option to delete the key, which we who use the classic theme do.

**Comment by Anixx** [comment]
That's OK for me.

**Comment by Anixx** [comment]
Consider also to add options to copy those colors and window metrics to the keys that define the WinXP logon dialog appearance. See here for details: https://www.reddit.com/r/windows/comments/114jwbg/comment/j8y7omn/?utm_source=share&utm_medium=web2x&context=3

**Comment by Anixx** [comment]
HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\ThemeManager - determines if the theme active in logon dialog.

HKEY_USERS\.DEFAULT\Control Panel\Colors - colors of logon dialog

HKEY_USERS\.DEFAULT\Control Panel\Desktop\WindowMetrics - window metrics of logon dialog

HKEY_USERS\.DEFAULT\Control Panel\Desktop - user preference mask of logon dialog

**Comment by Abdelrhman-AK** [comment]
I'll implement them too

**Comment by Anixx** [comment]
I think, essentially each customization key has a counterpart in HKEY_USERS.DEFAULT

**Comment by Abdelrhman-AK** [comment]
Yes, you're right.
Customizing the classic colors, metrics and fonts are the essential ones.
