### ISSUE TITLE
I think, the mention of Otvdm is confusing

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#118]
First, it is not an app, but rather a framework to run apps. Some apps it can run are Win 1.0/2 based, so they have distinct appearance, not representative of the usual classic theme we are used to (Win 95-Win7).

Second, even its official name, I think, is Winevdm...

So, I think, mentioning it may be confusing:
![изображение](https://user-images.githubusercontent.com/1271736/224555970-5c9a593b-debb-4ef4-94b8-a55feccb76d3.png)

I suggest to replace it with "CPU-Z", a common modern application that always runs unthemed.

**Comment by Abdelrhman-AK** [comment]
OK. I'll change this
