### ISSUE TITLE
Feature Requests: Relabeling/Hex-RGB/Compress Release

### ISSUE THREAD

**Issue by big610** [Abdelrhman-AK/WinPaletter#12]
Feature Requests: 

https://github.com/Abdelrhman-AK/WinPaletter/issues/4
Needs more definement to find.  The User who posted & myself had to look around. I actully did know, then forgot.
Reason the hover mode fooled us.
Add to your main page https://github.com/Abdelrhman-AK/WinPaletter.
Need Directions or screenshot with new labeling. Reason: your pictures can't show the hover name.
So the reason for a re-design to replace the mouse hover hidden.
Relabeling:
Currently says "Create New Theme (Palette) File.
Sugest the name has "Default Reset" added into it. Or a seperate labled Default button, for easy changes, reset & indefication.
Reason for lableing return to default button easily seen.
The file "Save Theme File" perhaps add Export/Import to name.

Main Window, ability to get into to see current Hex/RGB assigned color. Then you can write them down or screenshot, with #'s.
Your choice how/where, if you would assign the # into each line. If only one # fits comfortbly, add a expand to see both RGB & Hex. Need at leat one Number.
Code the line color number, when Windows Default color is on next to the RGB/Hex # show the word Default or D; Then when changed to a custom the "Default or D" disapears. 
Having the exact # ability you can immediately know if your color is slightly off, or was changed, bumped, etc.
Knowing the true Windows Default RGB/Hex #'s, helpful, for customizing. 
Particularly if you have multiple units you could pick assign different Hex/RGB for units, as a watchdog, or units needing attention are colored a particular color till fixed, then changed to another color or back to default. Also particular users or units in general, could be given a particlar color.
Abilty to say, Check if a unit has true default, with a easily seen Default On or Off, Custom Mode.
Windows Default Set  &/or Custom Set, on main window. Having easy ideficataion you know if anyone has touched, experimented the unit.

Zip compress the .exe release. Then when unzipped, you see the true Date/Time released. Currently when downloaded becomes the Date/Time of download. Eliminates confusion for those that save & backup every file, & those getting the correct download, you know immediately which is which, by Real Time/Date.

**Comment by Abdelrhman-AK** [comment]
**Thanks for your feedback**, I'll try to include these suggestions into next versions.
