### ISSUE TITLE
Option to remove the NavBar from Explorer?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#122]
Explorer Patcher does it via registry, this was listed in the feature request regarding EP. You marked it as completed, but I do not see this option yet.

**Comment by Abdelrhman-AK** [comment]
I closed #105 as most items in it are done except for Disable navigation bar, it didn't work with me at all. I'll try again

**Comment by Anixx** [comment]
Oh, my bad! Without EP it only works in open/save dialogs!
https://winclassic.boards.net/thread/132/removing-navigation-bar-windows-explorer?page=1&scrollTo=12454

Still can beof use.

**Comment by Anixx** [comment]
You can mension that it works in open/save without EP and everywhere with EP.

**Comment by Abdelrhman-AK** [comment]
Okay
