### ISSUE TITLE
This option is not for Win11 only

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#123]
![изображение](https://user-images.githubusercontent.com/1271736/225642750-46a596e9-7094-43dc-b832-099b4c14136f.png)

Windows 7 and Windows 8.1 allows to chose between Ribbon and command bar.

**Comment by Abdelrhman-AK** [comment]
> Windows 7 and Windows 8.1 allows to chose between Ribbon and command bar.
>

When I tested registry modification to enable Windows 10 ribbon for Windows 11, it didn't work at all, and so with a clean-installed Windows 11 in a VM. This item really modifies `HKEY_CURRENT_USER\Software\ExplorerPatcher : FileExplorerCommandUI` while 
 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked : e2bf9676-5f8f-435c-97eb-11607a5bedf7} ` doesn't and so I made EP is a requirement.

I'll try again with this reg entry in Windows 8.1

---

> I suggest creating a separate "Controls options" tab that would allow to chose the common controls used in theme (SysListView32 vs IconView, Ribbon vs Command Bar and context menu style).
>

- I didn't know before that EP requires Windows 10, not 11 only. I'll change its section and move it into a new tab.
- The item that manages context menu (WinUI3\Classic) is specified for Windows 11 so I won't move it.

> In the future also, possibly, the style of open/save dialogs, taskbar (Win11 vs Win10), but the last one is done better with EP rather than with registry.
>

I'll try to implement them gradually in the near future.
