### ISSUE TITLE
Change Taskbar programs menu colour

### ISSUE THREAD

**Issue by Anutim** [Abdelrhman-AK/WinPaletter#127]
Unfortunately I can't link any documentation on the element as I haven't been able to find out anything about it lol.

But here's a screenshot of what I'd wanna change the colour of: 
![image](https://user-images.githubusercontent.com/18088499/228355239-fe9711ec-54c4-48a3-b38f-571a3e7e3c97.png)

(Just r-click on a program from the taskbar)

**Comment by Abdelrhman-AK** [comment]
Unfortunately, there is no possible way to modify it, even if all colors are changed with applying accent on taskbar enabled.

![Screenshot 2023-03-28 230332](https://user-images.githubusercontent.com/59510211/228366618-a4c9cb76-70a7-4a24-ac47-8986a8131186.png)
