### ISSUE TITLE
Feature Requests : Add support for directly changing colors of win32 controls

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#13]
First of all, thank you for your great project, which allows you to add some order to the mess that modern Windows represents with regard to personalization.

In the Win32 controls configuration window (Win32UI), indicate that changing these colors requires a session restart. Indeed, it is; but there are many older win32 control color changing programs that support changing colors directly, just by clicking the apply button (without having to restart the session). This has been possible since the very first version of Windows (so I guess it shouldn't be very complicated to implement).

So my suggestion/request is to add support for directly changing the color of win32 controls, with no logout/login required.

There are many older tools with similar functionality; however, some parameters (such as menubar or menuhilight) were added later, so the old tools do not change all colors.
If you want examples, I can give you the links (however, I have only a few open-source examples, and none in VisualBasic.NET).

**Comment by Abdelrhman-AK** [comment]
I'll be very thankful for you if you give me a repos/code for applying the colors without restart (Like the apps you mentioned)

**Comment by OrthodoxWindows** [comment]
There are actually a few sources :

1. Two window metrics and window font configuration programs. It's not the colors, but the operation seems quite similar (it's also about modifying the appearance of win32 programs, by modifying the registry), and these two programs allow you to apply the changes without any session restart. The code is recent (probably developed under Windows 10), in C++. https://github.com/Tatsu-syo/ReMetrics https://github.com/Tatsu-syo/noMeiryoUI

2. The settings page for a program called SimpleClassicTheme, designed to make it easier to enable the classic theme in modern Windows. The developer switched the page to "archive" mode because he recently decided to switch his program to closed source. The development of this configuration page is very recent (probably done under Windows 10), and it is C# code. The code also contains something to change window metrics and fonts, but that's not the point here. https://github.com/AEAEAEAE4343/SimpleClassicTheme/tree/2f1fee13a7e8b40f69e1314f8a5010ed7ab2fe44/SimpleClassicTheme/Theming

3. An old Win16 program named WINCOLOR that I found on archive.org. For some reason the source code is included. This is c code. As it is, the program opens in OTVDM, but works poorly (some colors change automatically when opened). Due to the date of the program, many colors are not included. The license of the program is unknown. https://archive.org/details/msdos_shareware_fb_WINCOLOR

4. Windows NT4 sources, but of course this is legally risky.

Sorry if English is bad, it's not my mother language.

**Comment by Abdelrhman-AK** [comment]
**Thank you for your efforts!!**
I'll inspect these sources, and if I manage to apply colors without restart, I'll rewrite the code and remove both restarting explorer and rescue box.
