### ISSUE TITLE
What des the parameter "shell icon size" do?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#133]
It seems to have no effect?

![изображение](https://user-images.githubusercontent.com/1271736/230978105-22901c6b-8e79-4fde-ab5c-acc62e395f11.png)

**Comment by Abdelrhman-AK** [comment]
I found it while navigating through metrics registry, and it didn't have effects.

It may be useful only for Windows XP as you said there: #132
