### ISSUE TITLE
The icon of inactive app in taskbar is faded on preview

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#134]
![изображение](https://user-images.githubusercontent.com/1271736/230986806-a4579084-cd2e-496d-a417-eee69dab78ff.png)
I have never seen this effect in Classic theme, I am not sure about other themes.

**Comment by Abdelrhman-AK** [comment]
I did it intentionally (as if there are two applications are open, one is active and the other is not).

#### Active:
 ![ActiveApp_Taskbar](https://user-images.githubusercontent.com/59510211/231284224-3cd50256-b087-434b-8ae9-8e7d78f1180f.png) ![AppPreview](https://user-images.githubusercontent.com/59510211/231284227-ee1cd8e5-e367-4a45-b389-33637ddfbec3.png)
---

#### Inactive:
![InactiveApp_Taskbar](https://user-images.githubusercontent.com/59510211/231284215-6a99883a-1870-4c1a-b121-7e2df315d3a2.png) ![AppPreviewInActive](https://user-images.githubusercontent.com/59510211/231284229-60fd0f07-62c9-4c3a-a247-e95bcb552fbb.png)

**Comment by Anixx** [comment]
But this does not reflect how the theme behaves in reality...

**Comment by Abdelrhman-AK** [comment]
The only point is that there are two applications.
I know that there is conflict between icons colors and selected colors, so I can change both into two colorful icons.
