### ISSUE TITLE
Logging-off Text Should Be Different in US English

### ISSUE THREAD

**Issue by BondingforToday** [Abdelrhman-AK/WinPaletter#140]
In the US English language, the line 
  "Are you sure from Logging-off?"
should be
 "Are you sure you want to log off?"

Current text:
![Current text](https://user-images.githubusercontent.com/91759929/232249416-1516b771-1edb-434a-ad2e-70186fd461f0.png)

Corrected translation:
![Corrected translation](https://user-images.githubusercontent.com/91759929/232249424-5fb2534e-9653-4577-89c9-29cfd94f8c17.png)

**Comment by Abdelrhman-AK** [comment]
I'll correct it.
