### ISSUE TITLE
Option to disable inactive title bar color

### ISSUE THREAD

**Issue by Lum1nial** [Abdelrhman-AK/WinPaletter#143]
The latest version of WinPaletter as of the submission of this issue includes an option to change but not to disable the inactive title bar color. The only way to disable the inactive title bar color is to edit the registry, HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM, and delete the AccentColorInactive key.
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/75108295/79685adc-2d78-400a-85b1-bc78c751dab1)
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/75108295/051206fb-7ee9-4138-bbea-4d1d7e2f1c7e)

This can be noticed with Chrome's inactive title bars.
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/75108295/ce69504c-10f0-46ac-88c2-c6fd939e53c1)
Without AccentColorInactive:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/75108295/b4850b91-582e-4f74-950b-f50715d1fe17)

**Comment by Abdelrhman-AK** [comment]
Actually it is not working in most Windows applications except for Google Chrome (as it renders a custom titlebar and not using the native titlebar).

https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/774f4c25-a5b4-4c40-adaa-be2bd9e5bbea
