### ISSUE TITLE
The scales in RGB color picker look misleading

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#148]
![изображение](https://github.com/Abdelrhman-AK/WinPaletter/assets/1271736/c9333b0d-4231-4e89-a620-9bde8b49763a)

One could expect red to show saturattion of red, blue - saturation of blue and green - saturation of green (that is, gradint from white or black to full that color). The current colors on the scale are unclear what they signify at all.

**Comment by Abdelrhman-AK** [comment]
This is in component/assembly I used (Cyotek Color Picker: https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker) and I can't control/change this behaviour

Actually it is not a problem, each bar will show you the color with combining R, G and B (Not showing R, G, B individually).
In another way, set two channels to `0` and you will find the other unmodified channel are shown correctly.
