### ISSUE TITLE
Crash on Application start

### ISSUE THREAD

**Issue by shiftbiter** [Abdelrhman-AK/WinPaletter#153]
The application crashes right on startup, with an InvalidCastException

## **WinPaletter Log**
```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Dienstag, 13. Juni 2023 23:01:44"
OS = "Microsoft Windows 11 Pro - 10.0.22621.1702 - 64-bit"
WinPaletter.Version = "1.0.7.7"

'Error details
'-----------------------------------------------------------
Exception.message = "Ungültige Konvertierung von der Zeichenfolge  in Typ Integer."
Exception.type = "System.InvalidCastException"
Exception.stack.trace = {
   bei Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   bei Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
   bei WinPaletter.CP.Structures.MetricsFonts.Load(MetricsFonts _DefMetricsFonts)
   bei WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreExtractionThemePack)
   bei WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "ToInteger @ Microsoft.VisualBasic"
Exception.assembly = "Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll"
Exception.HRESULT = "-2147467262"
Inner.exception.message = "Die Eingabezeichenfolge hat das falsche Format."
Exception.type = "System.FormatException"
Inner.exception.stack.trace = {
   bei Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   bei Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
         }
Inner.exception.data = "There is no included data in Inner exception"
Inner.exception.target.sub_function = "ParseDouble @ Microsoft.VisualBasic"
Inner.exception.assembly = "Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Inner.exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll"
Inner.exception.HRESULT = "-2146233033"
```

**Comment by Abdelrhman-AK** [comment]
Can you take screenshot to registry `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` ?

**Comment by shiftbiter** [comment]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"IconTitleWrap"="1"
"BorderWidth"="-15"
"CaptionFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"CaptionHeight"="-330"
"CaptionWidth"="-330"
"IconFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,00,\
  00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"MenuFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,00,\
  00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"MenuHeight"="-285"
"MenuWidth"="-285"
"MessageFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"ScrollHeight"="-255"
"ScrollWidth"="-255"
"Shell Icon Size"=""
"SmCaptionFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,\
  00,00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"SmCaptionHeight"="-330"
"SmCaptionWidth"="-330"
"StatusFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"PaddedBorderWidth"="-60"
"AppliedDPI"=dword:00000060
"IconSpacing"="-1710"
"IconVerticalSpacing"="-1125"
"MinAnimate"="1"

**Comment by Abdelrhman-AK** [comment]
Change `Shell Icon Size` to 32 and reopen WinPaletter
