### ISSUE TITLE
update error : "oldWinpaletter.trash" already exist

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#154]
## **Describe the bug**
after update automatically, "oldWinpaletter.trash" is not deleted
so when i trying automatic update later (maybe first button of 3 buttons), write error occured.

## **WinPaletter Log**
sadly I accidentally close error window so only have few lines

## **Screenshots/Screen records**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/93962018/5e4fece1-afc8-46cf-9a55-b2490f95d22b)

If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
few solutions i can think:
1. just overwrite it. but this can erase user data (ex: they named thiers "Oldwinpaletter.trash")
2. must delete it after update
3. change directory path to "%TEMP%\random string folder". Download folder is not safe enough

+i'm on 1.0.7.6

**Comment by Abdelrhman-AK** [comment]
Try to delete this file manually, and I will fix this issue.

> I found WinPaletter log directory. It was your name, not program name :)

> .net framework apps create app data folder name with developer name first then application name in a subfolder.
