### ISSUE TITLE
1.0.7.7 metric and font eror

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#155]
## **Describe the bug**
When I opening "metric and font" settings window, the program crashes

## **WinPaletter Log**
[3.34.23 15-6-2023.txt](https://github.com/Abdelrhman-AK/WinPaletter/files/11749639/3.34.23.15-6-2023.txt)
[3.32.26 15-6-2023.txt](https://github.com/Abdelrhman-AK/WinPaletter/files/11749640/3.32.26.15-6-2023.txt)

## **Screenshots/Screen records**
Don't add screenshot if you already wrote WinPaletter Log.

If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
I used WinPaletter Store and edit "AMOLED" theme before

**Comment by Abdelrhman-AK** [comment]
I'll fix this issue. It is not related to this Store theme

**Comment by Abdelrhman-AK** [comment]
- Please run 'SFC /scannow' in Command Prompt as administrator and restart your Windows.
- This was a bug in patching `imageres.dll` to change Startup sound
- Don't use beta versions below 1.0.8.0. Wait for the new version it will be released soon
