### ISSUE TITLE
Change system tray icons overflow ("Show hidden icons") flyout color even if "Show accent color on Start and taskbar" is enabled

### ISSUE THREAD

**Issue by ELowry** [Abdelrhman-AK/WinPaletter#158]
Hi there!

I am using a pretty bold (red-ish) accent color and have WinPaletter toning down some of the more garish default ways it is used.

One of the things I really like about this is that I can have a very slightly red hued taskbar and start menu with the "Show accent color on Start and taskbar" windows setting active, instead of using the overly-saturated accent color:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/7792033/c12f54bb-f216-49d5-b5c5-7e68be06cf18)

This works great; however, there is one part of the system that does not follow this setting, the system tray icons overflow:

![Screenshot 2023-06-16 094516](https://github.com/valinet/ExplorerPatcher/assets/7792033/1e439ece-95ed-44e2-a531-dae986b85908)

This results in a jarring contrast between the taskbar and the overflow menu. Furthermore, it makes it extremely hard to see some icons (red on red) in the overflow.

Is there some way this menu could be made to follow the toned-down red-hued taskbar color without disabling the "Show accent color on Start and taskbar" option in Windows (making the taskbar a neutral gray as a result)?

**Comment by Abdelrhman-AK** [comment]
You can simply change this color to a darker color manually.

![Screenshot_20230616-112101_Chrome.png](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/d5f0f09e-1e78-46da-b468-a6174750bcb1)

**Comment by ELowry** [comment]
I looked like 5 times, and still missed it XD.

It may be good to try and fit it into the preview somehow?

**Comment by Abdelrhman-AK** [comment]
It is difficult to put tray overflow area in the preview, it is occupied by Action Center part.

**Comment by ELowry** [comment]
Gotcha, no worries. it worked great!
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/7792033/9e8e1d36-a5ed-48dd-81ee-661387b541f3)
