### ISSUE TITLE
Redundant UAC dialogs

### ISSUE THREAD

**Issue by TBugReporter** [Abdelrhman-AK/WinPaletter#159]
Steps to reproduce:

1. Run WinPaletter 1.0.7.6 from a **non**-Administrator account.

2. Click the "Classic Colors" icon.

3. Make any small change to the settings, such as the one I tried:

a. Click "Selection Objects" on the left.

b. Click the color swatch next to "Menu bar".

c. Use the Color Picker that appears to choose a different color.

d. Click "Select" to close the Color Picker.

e. Click "Quick apply".

f. Enter your Administrator password into the UAC prompt.

Expected Result:

The UAC prompt goes away and the change is made.

Actual Result:

The UAC prompt goes away, but immediately comes back - possibly more than once.  (I can't figure out what determines the number of times it reappears.)

**Comment by TBugReporter** [comment]
I thought that this would be a matter of collecting the changes and making them all in the same elevated process; I guess I don't understand the Windows security stuff as well as I thought.

The settings change you pointed me to does eliminate the redundant UAC prompts; thank you for the assistance.  (Now I just have to figure out which colors I need to change. 🙂)

**Comment by Abdelrhman-AK** [comment]
Unfortunately, I can't make modifying all registry keys in one process. Each item is changed/modified by its code line and so there are redundant/many UAC prompts.
