### ISSUE TITLE
Themeui.dll still offers 5 Win32 schemes

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#16]
Default Windows 2000:
Themeui.dll, -854 

High-contrast white:
Themeui.dll, -853

High-contrast black:
-850,  -851,  -852

I think it would be a good idea to also offer the default Win95 scheme, as well as those stored in registry at \HKEY_CURRENT_USER\Control Panel\Appearance\Schemes.

**Comment by Abdelrhman-AK** [comment]
I'll implement this in the next version! Thanks for your feedback
