### ISSUE TITLE
Always Not Responding Applying Metrics & Fonts

### ISSUE THREAD

**Issue by YKefasu** [Abdelrhman-AK/WinPaletter#161]
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/129555908/00ff7a86-8f2d-426d-a4e0-91ff0bcbefdc)
After Applying Metrics & Fonts few times on v1.0.7.8-Beta, now its Always Not Responding
tried using [v1.0.7.6-Stable](https://github.com/Abdelrhman-AK/WinPaletter/releases/tag/v1.0.7.6) still Not Responding

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/129555908/d53a7f9b-0de4-4adb-8df6-4306513b15aa)

**Comment by Abdelrhman-AK** [comment]
Does this issue still persist or not?

**Comment by YKefasu** [comment]
> Does this issue still persist or not?

Sorry bothering, i'm just need to restart windows
