### ISSUE TITLE
chocolatey

### ISSUE THREAD

**Issue by xLexih** [Abdelrhman-AK/WinPaletter#168]
## **What is your new idea or feature?**
Adding WinPaletter as a package to [chocolatey](https://community.chocolatey.org/)

## **You can mention\include the following *if possible* to make implementing the idea easier:**
There's a section inside the [docs for chocolatey](https://docs.chocolatey.org/en-us/features/create-packages) about creating new package

## **Additional context**
It would be handy to just `choco install WinPaletter` and get the program installed :)

**Comment by Abdelrhman-AK** [comment]
I'll read documentation, and then I'll try implementing your idea.

**Comment by Abdelrhman-AK** [comment]
Here you are:
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Get-WinPaletter#3-chocolatey
