### ISSUE TITLE
Win32 WindowMetrics support?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#17]
Are there any plans to implement Window Metrics support (button size, window frame size, etc)?

**Comment by Abdelrhman-AK** [comment]
I'm focusing now on changing colors mainly, I might implement this in the future

**Comment by Anixx** [comment]
http://systemmanager.ru/win2k_regestry.en/58584.htm

http://systemmanager.ru/win2k_regestry.en/58842.htm
