### ISSUE TITLE
Issue: is that bug? so that text box is black - also there is font bug 

### ISSUE THREAD

**Issue by Makezu90** [Abdelrhman-AK/WinPaletter#175]
## **Describe the bug**

Not sure, but i checked README and it has screenshot and it has not that black box. I would like to use apps dark theme instead white, but its that happens also on if select in app mode white theme. I do not have any custom theme. I selected firstly dark/white default theme on windows settings and then my custom winpaletter theme.

Font bug so its wrongly scaled/blurry.

## **WinPaletter Log**
If an exception error occurred, press on `copy details` and paste them here. 
The details will include info about WinPaletter version, date, current OS, exception error message & Stack Trace.

## **Screenshots/Screen records**
Don't add screenshot if you already wrote WinPaletter Log.

If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/89158176/58af251f-5af3-4256-a0dd-a5eb38650e63)

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/89158176/e7fac934-0885-4dbc-84db-2846d1e5ecd7)

## **Additional context**

WinPaletter version: 1.0.8.0

**Comment by Makezu90** [comment]
Needed delete old saved file theme and create new one. Not sure what was issue, but now everything again is fine.

**Comment by Makezu90** [comment]
Needed delete old saved file theme and create new one. Not sure what was issue, but now everything again is fine.

**Comment by Abdelrhman-AK** [comment]
It is not a bug. These are remnants of classic colors.
Read this: https://github.com/Abdelrhman-AK/WinPaletter#-classic-colors
