### ISSUE TITLE
When applying changes WinPaletter goes non responding on Applying Windows Metrics and Fonts

### ISSUE THREAD

**Issue by maneum1** [Abdelrhman-AK/WinPaletter#176]
## **Describe the bug**
When applying changes WinPaletter goes non responding when reaching step "Applying Windows Metrics and Fonts"

## **WinPaletter Log**
WinPaletter is frozen, so I can't copy any log.

## **Screenshots/Screen records**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/22628333/c0192965-e2e2-491d-a4eb-22735d5d73c0)

## **Additional context**
I'm on windows 10 vs 22H2
Loaded latest WinPalletter version v1.0.8.0-Stable today

I saw the other similar recorded issues but the solutions sadly did not to work for me.

**Comment by Abdelrhman-AK** [comment]
- Even this didn't work: https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts ?

- Are there any other programs open with WinPaletter or not?

**Comment by maneum1** [comment]
I'm ashamed, ...  yes that worked   Thanks for pointing me to it.

**Comment by Abdelrhman-AK** [comment]
You're welcome!
