### ISSUE TITLE
Desktop icons get their spacing reduced

### ISSUE THREAD

**Issue by Malix-Off** [Abdelrhman-AK/WinPaletter#178]
## Problem

Desktop icons get their spacing reduced

## Occurrence

When applying some edits (accents colors afaik)

## Cause

This is due to

- `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics\IconSpacing` (Registry Editor)
- `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics\IconVerticalSpacing` (Registry Editor)

Getting set to `-720` instead of the original `-1125`

**Comment by Abdelrhman-AK** [comment]
Open [Metrics and Fonts\Icons](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Metrics-and-Fonts#2-spacing) and set both spacings to `75` and then press on [Load into current theme and apply the theme](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Metrics-and-Fonts#4-actions) or [Quick apply](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Metrics-and-Fonts#4-actions)

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732308221) from @Abdelrhman-AK :
  > Open [Metrics and Fonts\Icons](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Metrics-and-Fonts#2-spacing) and set both spacings to `75` [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732308221)

  It was already the case, as I think is the default value

**Comment by Abdelrhman-AK** [comment]
Yes it is the default one `(-1125 / -15 = 75)`. I thought that you changed it from WinPaletter.
Try to set it manually in registry by `-1125` and then try again with WinPaletter.

- Does this problem happen every time you apply a theme from the main form (even if it is `75` inside WinPaletter)?
- Do you use a higher DPI for your monitor or not?

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157) I thought that you changed it from WinPaletter. [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157)

  Nope, I didn't change it

  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157) Try to set it manually in registry by -1125 and then try again with WinPaletter. [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157)

  Yep, that's what I do every time

  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157) 
  > - Does this problem happen every time you apply a theme from the main form (even if it is `75` inside WinPaletter)?
  > 
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157)

  Every time i'm applying even a single accent color edit, even.
  I did install the "AMOLED" theme once, but did rest to the first theme by clicking on the "Reload first theme" button since.
  Is there a way I could wipe the "AMOLED" theme out of my system?
  
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157) 
  > - Do you use a higher DPI for your monitor or not?
  > 
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732311157)
  
  I do not think so, however, i'm using a display custom scaling of 125%
  ![windows display custom scaling of 125%](https://github.com/Abdelrhman-AK/WinPaletter/assets/76160668/2fdeee4d-a8fe-41f1-b4e7-4bd2f7936a31)

  If that can help

**Comment by Abdelrhman-AK** [comment]
> Every time i'm applying even a single accent color edit, even.
I did install the "AMOLED" theme once, but did rest to the first theme by clicking on the "Reload first theme" button since.
Is there a way I could wipe the "AMOLED" theme out of my system?

Store themes are stored as files in `%localappdata%\Abdelrhman-AK\WinPaletter\Store`, but when you apply the default theme, store theme won't have effects on your system.

(Its button in main form toolbar: ![alt text](https://github.com/Abdelrhman-AK/WinPaletter/blob/master/Media/Wiki/MainFormParts/2_2.png?raw=true))

> I do not think so, however, i'm using a display custom scaling of 125%

I'll do some tests with DPI 125% to know if icons spacings are effected with high DPI or not.

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732315872) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/178#issuecomment-1732315872) I'll do some tests with DPI 125% to know if icons spacings are effected with high DPI or not.

  See https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732323161

**Comment by Abdelrhman-AK** [comment]
- Using 125% DPI from the menu will fix the issue. Custom DPI value is the cause of this issue

![0](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/81926e20-6a4d-4a9d-8e60-045b087fe549)

![1](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/f41e49e1-a845-442a-9c30-4124c89376a4)

https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1740009145
