### ISSUE TITLE
Icon File Corruption

### ISSUE THREAD

**Issue by Malix-Off** [Abdelrhman-AK/WinPaletter#179]
## Problem

Icon files got corrupted
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/76160668/dda4c3fd-144b-47e3-9154-a11684d720ee)
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/76160668/f12a291a-10fa-42c7-a594-5d33029eb317)
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/76160668/45fd04b8-6d4d-4934-b135-b904433fae83)
Also, the spinning dots in boot screen has disappeared, even when the "Spinning dots in boot screen" option has its checkbox checked in `Windows Effects/For Windows 11 only`

## Occurrence

When applying some edits (AMOLED theme (even after rolling back to original))

## Cause

Unknown

## More Information

Using display custom scaling of 125%
![windows display custom scaling of 125%](https://user-images.githubusercontent.com/76160668/270110001-2fdeee4d-a8fe-41f1-b4e7-4bd2f7936a31.png)

**Comment by Malix-Off** [comment]
## Update

Disabling custom scaling fixed the small icon problem, but not the disappearance of the spinning dots in boot screen

**Comment by Abdelrhman-AK** [comment]
Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\BootControl` and delete `BootProgressAnimation`

**Comment by Abdelrhman-AK** [comment]
- And give me a screenshot to `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` with these small icons not solved.

- As much as I remember, I faced issue of small icons while developing Metrics and Fonts last year.

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732324827) from @Abdelrhman-AK :
  > Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\BootControl` and delete `BootProgressAnimation`

  Done, i'm going to test if that worked

- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732324827) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732324827) give me a screenshot to `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732324827)
  
  ![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/76160668/7e5c76b8-b8b1-4a22-9ed6-b39fc12c94cf)

**Comment by Abdelrhman-AK** [comment]
Set `SmCaptionHeight` and `SmCaptionWidth` to `-330` and logoff and logon and tell me if it is fixed or not.

**Comment by Malix-Off** [comment]
## Update

- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732325952) from @Malix-Off :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732325952) i'm going to test if that worked [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732325952)

  It did not

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732326526) from @USER :
  > Set `SmCaptionHeight` and `SmCaptionWidth` to `-330` and logoff and logon and tell me if it is fixed or not.

  It did not work

**Comment by Abdelrhman-AK** [comment]
Set your custom scaling to 100%, logoff and logon, [Download this ZIP](https://github.com/Abdelrhman-AK/WinPaletter/files/12706643/0.zip), extract it and merge the extracted registry file, logoff and logon, edit your DPI as you want, logoff and finally logon.

**Comment by Abdelrhman-AK** [comment]
- For spinning dot, it cannot be fixed right now. WinPaletter only modifies `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\BootControl\BootProgressAnimation` and its disappearance is a weird thing for me.

- Anyway, you can try running `SFC /scannow` in command prompt as administrator. There is a weak possibility that this will fix spinning dots issue.

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732329480) from @Abdelrhman-AK :
  > Set your custom scaling to 100%, logoff and logon, [Download this ZIP](https://github.com/Abdelrhman-AK/WinPaletter/files/12706643/0.zip), extract it and merge the extracted registry file, logoff and logon, edit your DPI as you want, logoff and finally logon.

  That worked, thanks a lot.
  It sure was caused because of the messing up of `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics`, which is weird because I didn't specify any settings on WinPaletter for those keys to be changed, unless the "AMOLED" theme has some?

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231) WinPaletter only modifies `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\BootControl\BootProgressAnimation` [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231)

  Yes.
  I deleted this key as you told me [here](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732324827) by the way

  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231) try running `SFC /scannow` in command prompt as administrator [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231)

  I tried `SFC /scannow`, `DISM /Online /Cleanup-Image /CheckHealth`, and `DISM /online /cleanup-image /scanhealth` (as instructed by [SpiritX MS MVP](https://answers.microsoft.com/en-us/profile/022c5ded-2afc-4a6a-a8a2-3f595b476368) [there](https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_taskbar/why-do-icons-in-the-taskbar-becomme-blurry-and/8db9e0eb-fdab-4a14-8109-402fa5704bcf).)

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231) try [this](https://gearupwindows.com/fix-spinning-dots-or-circle-animation-doesnt-appear-on-reboot-or-shutdown-screen-in-windows-11/) too [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732330231)

  I already tried before but it did not change anything.
  I suspect it was a setting embedded in the "AMOLED" theme.

**Comment by Abdelrhman-AK** [comment]
Make sure that you [disable Metrics](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Effects#1-enabledisable-lock-toggle) every time you apply a theme, and always check Store themes items. They are explained there: https://github.com/Abdelrhman-AK/WinPaletter/wiki/WinPaletter-Store-basics#6-themes-aspects-review

Even this didn't work with you? 
https://gearupwindows.com/fix-spinning-dots-or-circle-animation-doesnt-appear-on-reboot-or-shutdown-screen-in-windows-11/

**Comment by Abdelrhman-AK** [comment]
AMOLED and other Store themes will apply the edited aspects inside them, and so there is this problem
Read this: https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Effects#1-enabledisable-lock-toggle

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334386) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334386) Even this didn't work with you?
https://gearupwindows.com/fix-spinning-dots-or-circle-animation-doesnt-appear-on-reboot-or-shutdown-screen-in-windows-11/ [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334386)

  As the time I wrote [that comment](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334197), no; but i'm going to test again

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334785) from @Abdelrhman-AK :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732334785) Read this: https://github.com/Abdelrhman-AK/WinPaletter/wiki/WinPaletter-Store-basics#6-themes-aspects-review

  I read that already, and followed those guidelines when the bugs happened

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732337757) from @Malix-Off :
  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732337757) i'm going to test again

  It did not work

**Comment by Abdelrhman-AK** [comment]
That is good. 
Did you use Windows 98 theme in Store? This theme disables animation that you have just enabled in control panel.

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732383979) from @Abdelrhman-AK :
  > That is good. [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732383979)

  Absolutely, thanks for helping mate ❤️
  The issue stays not fixed in the software though

  > [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732383979) Did you use Windows 98 theme in Store? [⋯](https://github.com/Abdelrhman-AK/WinPaletter/issues/179#issuecomment-1732383979)

  Nope, only the "AMOLED" theme and custom personal edits

**Comment by Abdelrhman-AK** [comment]
> Absolutely, thanks for helping mate ❤️

You're welcome bro!

> The issue stays not fixed in the software though

I can't fix all issues that happen because of high DPI. I tried several methods before but unfortunately they didn't fix these issues properly. I'll try to fix small icons issue in next updates

**Comment by Abdelrhman-AK** [comment]
- I have just known the issue, it is a bug in Windows.
- When `CaptionWidth` registry value is too low (or classic button width is lower than `18` in WinPaletter) with custom scaling is made (not from the first scaling combo box menu), icons will be extremely small.
- To solve it, keep classic button width `18` or higher in WinPaletter, logoff and logon.
- You are using 125% DPI, you should select it from the menu and dismiss custom DPI value that you manually enter.
