### ISSUE TITLE
Crashes every time I hit apply on Win 11

### ISSUE THREAD

**Issue by Mac3DX** [Abdelrhman-AK/WinPaletter#180]
I'm not an expert but I would like to report my experience with the App. I'm using Win 11 latest version and every time I change something and press apply the app no longer responds. I also can't change the color and patterns of the mouse pointer.

Thanks
Ricardo

**Comment by Abdelrhman-AK** [comment]
Try this and tell me if it worked: https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts

**Comment by MuscularPuky** [comment]
> Try this and tell me if it worked: https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts

Not work for me

**Comment by Abdelrhman-AK** [comment]
At which phase (in theme log) does it crash?

**Comment by MuscularPuky** [comment]
> At which phase (in theme log) does it crash?

All operations are done.
even I don't modify imageres.dll. and no errors.
maybe 3rd party conflict?

**Comment by MuscularPuky** [comment]
> > At which phase (in theme log) does it crash?
> 
> All operations are done. even I don't modify imageres.dll. and no errors. maybe 3rd party conflict?

오류 있는 응용 프로그램 이름: Explorer.EXE, 버전: 10.0.25967.1000, 타임스탬프로: 0x415d6b52
오류 있는 모듈 이름: Taskbar.View.dll, 버전: 2023.25605.0.0, 타임스탬프: 0x6501bc7b
예외 코드: 0xc000027b
오류 오프셋: 0x00000000000191aa
오류 처리 ID: 0x844C
오류 응용 프로그램 시작 시간: 0x1D9FE928D9EF7E9
Faulting 응용 프로그램 경로: C:\WINDOWS\Explorer.EXE
Faulting 모듈 경로: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll
Report Id: c38852b5-b9fc-41d9-8948-13505a75c2a9
Faulting 패키지 전체 이름: 
Faulting 패키지 상대 응용 프로그램 ID:  

or Windows bug??

**Comment by Abdelrhman-AK** [comment]
It is mainly a Windows bug.
Try disabling explorer restart: https://github.com/Abdelrhman-AK/WinPaletter/wiki/Disable-Explorer-restart
