### ISSUE TITLE
Exception 0xe0434352

### ISSUE THREAD

**Issue by Alloyd031** [Abdelrhman-AK/WinPaletter#181]
## **Describe the bug**
After running updated version of WinPaletter i get the exception 0xe0434352.

## **WinPaletter Log**
No log

## **Screenshots/Screen records**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/71263641/b8d14810-1d54-4a82-a4f3-3ae522a470b3)

## **Additional context**
No additional context.

**Comment by Abdelrhman-AK** [comment]
This issue may be related to .NET framwork as I read online. These lines may help you:

```
DISM /Online /Cleanup-Image /CheckHealth
DISM /Online /Cleanup-Image /ScanHealth
DISM /Online /Cleanup-Image /RestoreHealth
SFC /Scannow
```
Run them in Command Prompt as Administrator

**Comment by Alloyd031** [comment]
It didn't help

**Comment by Abdelrhman-AK** [comment]
Open WinPaletter to make the error occurs again.

Then open Event Viewer (search for it in Windows start) and open both Application and System parts, open the most recent events that have error icon and related to WinPaletter or .NET framwork and tell me what you found.

![images.png](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/7e089661-1eb7-458a-be97-c850623255a4)

**Comment by Alloyd031** [comment]
Ok, now it works after switching the taskbar style in ExplorerPatcher properties.

**Comment by Abdelrhman-AK** [comment]
That's weird. 
I'll test it myself and if I found a problem in WinPaletter itself, I'll fix it.
