### ISSUE TITLE
Amoled theme issues

### ISSUE THREAD

**Issue by oMaikeru** [Abdelrhman-AK/WinPaletter#182]
## Amoled theme issues
there are a lot of white spaces here and there and i dont think they are supposed to be there, visual effects text in performance options is white and buggy.
also is there any discord or any forum where i can get some help?

## Screenshots
![Screenshot 2023-10-10 183730](https://github.com/Abdelrhman-AK/WinPaletter/assets/76801149/91c913d7-e1c8-4957-ad87-33aaea3d85f6)

**Comment by Abdelrhman-AK** [comment]
These issues cannot be solved by modifying registry only. You can use an external visual styles to reach perfectionism (search for them online)

To fix this accessibility issue, open Classic Colors, choose a preset then return to default preset (Aero fallback) and press on quick apply
![0](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/491a2ca9-6ff0-4cfb-882a-0e63b11356dd)
