### ISSUE TITLE
Running in Standard Account pulls Administrator Account Theme

### ISSUE THREAD

**Issue by SupahMario** [Abdelrhman-AK/WinPaletter#185]
## **Describe the bug**
Since  the file itself is marked as administrator only, attempting to run it as a standard user will bring up the UAC prompt and request an account to be used to escalate privileges. Whichever account you decide to use here will be the user that the program ends up pulling from, including the theme. Attempting to change the theme through here will also only affect said administrator account. This isn't the first time we've seen this issue occur -- other programs seem to encounter a similar issue as well.

## **WinPaletter Log**
If an exception error occurred, press on `copy details` and paste them here. 
The details will include info about WinPaletter version, date, current OS, exception error message & Stack Trace.

## **Screenshots/Screen records**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/40162488/65d9452a-f4ec-4940-b276-4e1515db7cfc)

## **Additional context**
Older builds seemed to not be marked as administrator only, and would only request the UAC prompt when applying the theme. This worked relatively fine, minus the amount of UAC prompts given. Could probably work around this by launching a process that applies everything as UAC itself. ...Or just not require it for the steps which only apply to the user itself.

**Comment by Abdelrhman-AK** [comment]
- I can undo mark as administrator, but there will be errors in patching imageres.dll (it is the reason of changing the program from normal to administrator)
- I will try to create a second separate process, to make UAC alert appears for one time
