### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by VicTycoon** [Abdelrhman-AK/WinPaletter#186]
![ShareX_26T9bMzbQN](https://github.com/Abdelrhman-AK/WinPaletter/assets/141869831/cdc430fa-e3a6-43ca-91b1-b9b4d2009d16)
I can change alpha in Titlebar color option, but when I apply the alpha back to 255

**Comment by Abdelrhman-AK** [comment]
I intentionally made it returns to 255 as this Windows part doesn't support alpha manipulation.
