### ISSUE TITLE
Problem with Classic Colors

### ISSUE THREAD

**Issue by VicTycoon** [Abdelrhman-AK/WinPaletter#188]
I'm looking like crazy where I can change this white part of the Control Panel in Classic Colors but I can't. I changed all the white colors in the theme to see if I could find which setting it is. Does anyone have a tip on how to change this color? It doesn't just occur in Control Panel, it occurs in some other programs that use the classic theme as well.
![explorer_TmhklhDWyE](https://github.com/Abdelrhman-AK/WinPaletter/assets/141869831/57d457ab-d63e-4d47-8af7-1ddb51c4c303)

**Comment by Abdelrhman-AK** [comment]
This is a bug in Windows itself. It can be fixed by using an external visual styles. 

For example you can try Rectify11 visual styles and it will be mostly fixed.
