### ISSUE TITLE
Less and basic options and more average user understandable UI

### ISSUE THREAD

**Issue by rasitensar** [Abdelrhman-AK/WinPaletter#190]
I really like the concept of WinPaletter but struggle to understand configurable options. Easier to use UI and more detailed preview of options would be very nice. (By more detailed I mean, add every act of of change to preview)

**Comment by Abdelrhman-AK** [comment]
- I know that there are people struggling with using WinPaletter. I tried to simplify the app as much as I can and created the [Wiki](https://github.com/Abdelrhman-AK/WinPaletter/wiki) to help users use WinPaletter.

- > I really like the concept of WinPaletter but struggle to understand configurable options

    You can tell me these options and I will simplify them If I can.

- I'll try to simplify the application in near future. UI will be heavily changed.
