### ISSUE TITLE
How do I completely delete WinPaletter? 

### ISSUE THREAD

**Issue by rasitensar** [Abdelrhman-AK/WinPaletter#191]
How can I delete the WinPaletter completely? I want to delete the changes that I've made with WinPaletter also

**Comment by Abdelrhman-AK** [comment]
1. Open metrics and fonts, enable the toggle, open from default Windows, press on quick apply:
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-Metrics-and-Fonts#4-open-from-default-windows

2. Open Settings > Uninstall. In theme restore section, select `Default Windows`, press on uninstall and finally you can delete WinPaletter.exe
