### ISSUE TITLE
Behavior:Win32/Execution.A!ml in MS defender

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#192]
## **Describe the bug**
not a bug. just fake positive (but fine in VirusTotal)

## **WinPaletter Log**
no log

## **Screenshots/Screen records**
Behavior:Win32/Execution.A!ml

If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
Is this solvable? I think it's purely MS's problem.

**Comment by Abdelrhman-AK** [comment]
I couldn't solve it at all. Maybe not signing the program is the cause of false positive.

I have sent WinPaletter executable for analysis in Microsoft website and it found nothing. You can send this file to check again.
https://www.microsoft.com/en-us/wdsi/filesubmission
