### ISSUE TITLE
After installing WinPaletter, I run it once and cannot rerun or delete it.

### ISSUE THREAD

**Issue by Tiara-11** [Abdelrhman-AK/WinPaletter#196]
## **Describe the bug**
Installation and removal were done using the method suggested in the link.
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Get-WinPaletter

How can I return the theme to Windows default settings and delete it?
The text in the file explorer window is black and very inconvenient. If I delete it, will it be restored to its original state? Please tell me how to restore the File Explorer window to its original state and how to delete WinPaletter.

## **WinPaletter Log**
Microsoft Windows 11 Home 23H2 [Version 10.0.22631.2506]

## **Screenshots/Screen records**
![스크린샷 2023-11-11 040952](https://github.com/Abdelrhman-AK/WinPaletter/assets/53861295/16dfba4b-60c4-49d7-b887-c8b52c6df6d6)

Found WinPaletter [Abdelrhman-AK.WinPaletter]
Starting package removal...
Uninstallation failed due to installation exit code: 3762504530

![스크린샷 2023-11-11 040912](https://github.com/Abdelrhman-AK/WinPaletter/assets/53861295/f0f43804-ce10-4412-8713-4e123d75c377)

**Comment by Abdelrhman-AK** [comment]
### You can try not using Winget, do all steps manually:
- Try rerunning it after getting the latest version from releases https://github.com/Abdelrhman-AK/WinPaletter/releases/tag/v1.0.8.1
- Reset to default Windows theme (Main form > Toolbar > Create new theme file from default Windows preferences > Apply theme) https://github.com/Abdelrhman-AK/WinPaletter/wiki/Main-form-parts#toolbar
- Uninstall WinPaletter from WinPaletter main form > Settings > Uninstall button below
