### ISSUE TITLE
🐞 [Bug] WinPaletter 1.0.8.2 beta gets stuck in  Metrics And Fonts

### ISSUE THREAD

**Issue by boromyr** [Abdelrhman-AK/WinPaletter#197]
## **Describe the bug**
- With the new beta 1.0.8.2 the theme application crashes when editing Metrics And Fonts when:
```json
"MetricsFonts": {
    "Enabled": true,
```
In the screenshot, you can see the debug message during the crash.

## **How to reproduce the bug**
- Try to apply 
[Dark.wpth.txt](https://github.com/Abdelrhman-AK/WinPaletter/files/13353534/Dark.wpth.txt)

## **Screenshots/Screen records**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/11a6b306-5fb5-4a93-867d-60819c36ad0b)

Windows 11 23H2 22635.2700

**Comment by Abdelrhman-AK** [comment]
- There are some users experiencing the same issue.
- Opening multiple applications and applying metrics causes this issue as Windows will send message to all open applications to update its metrics.

- Anyway, try doing this and tell meif it worked:
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts

**Comment by boromyr** [comment]
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts it worked thanks.

**Comment by Abdelrhman-AK** [comment]
You're welcome!
