### ISSUE TITLE
Is it possible to change the colour of the bar immediately below the title bar?

### ISSUE THREAD

**Issue by githubdotcomuser** [Abdelrhman-AK/WinPaletter#199]
I can't change the colour of the bar below the title bar. Only the title bar's colour changes. The bar in question only takes the default Windows light or dark colour.

---
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/46681247/4af86151-d210-4af7-8bec-285f73ae85e2)

**Comment by Abdelrhman-AK** [comment]
- It is not possible at all to change this color by registry edit.

- Using an external visual styles may change this color. Search online for visual styles for Windows 10 and apply it using SecureUxTheme tool (Get it from GitHub)

**Comment by githubdotcomuser** [comment]
> * SecureUxTheme

Is it possible to do it without using any visual styles and just entering a hex code to change its colour in the tool you suggested?

**Comment by Abdelrhman-AK** [comment]
Actually I don't know a method to do this currently. When I know a method, I'll implement it.

**Comment by githubdotcomuser** [comment]
> Actually I don't know a method to do this currently. When I know a method, I'll implement it.

Thanks! I guess I will just have to keep an eye on any future updates from you regarding this issue.
