### ISSUE TITLE
Windows 2000 / XP is still lacking from the set of pre-defined schemes

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#20]
There is "Windows Classic" scheme in WinPaletter, but it is not the same as to Windows 2000 / XP classic scheme, the button face color, for instance is different.

I hereby add the Windows 2000 /XP scheme reg file.
[Win2000.zip](https://github.com/Abdelrhman-AK/WinPaletter/files/9310586/Win2000.zip)

Also, the schemes were usually stored in registry at 
HKEY_CURRENT_USER\Control Panel\Appearance\Schemes

Currently WinPaletter does not load or store schemes to/from this place.

**Comment by Anixx** [comment]
The Windows 98 default is also apparently wrong: Windows 98 had a gradient in titlebar by default.

**Comment by OrthodoxWindows** [comment]
For the Windows 98 theme, it's because the real Windows 98 theme is the one called "Windows classic" in Winpaletter. The one called "Windows 98" is actually the scheme from Windows 95/Windows NT4.

**Comment by Anixx** [comment]
Thanks, so, to sum it up, "Windows 98 default" should be renamed "Windows 95 default", "Windows Classic" should be renamed "Windows 98 default" and Windows 2000/Me theme can be added from the reg file.

**Comment by OrthodoxWindows** [comment]
Yes, aterwards, it is also possible to name like this:
Windows Standard 2000/ME
Windows Classic 98
Windows Classic 95/NT4

I don't know if it's useful to add the Standard/Classic denominations.

**Comment by Abdelrhman-AK** [comment]
- Windows 10/11 don't have themes preset in registry except 5 schemes, so I decided to get all schemes from Windows 3.1 until Windows XP using virtual machines (i.e. these presets included in WinPaletter don't depend on user's registry)

- For Windows XP themes I used a virtual machine to extract the themes and I saw someone posted these themes online.
I mixed my themes and this one's themes for mistake, I'm sorry for that 😂. 

- I'll re-extract the schemes and re-integrate them properly, and will focus on renaming (Windows Standard 2000/ME - Windows Classic 98 - Windows Classic 95/NT4)

Thank you, both !

**Comment by Anixx** [comment]
Thanks.

Honestly, I do not know what's the purpose of having Windows 3.1 color schemes. The controls are very different so one cannot get Windows 3.1 experience even if they would want to.

You did a big work apparently on extracting these schemes from Windows 3.1 but it is not apparent how they can be useful for anyone.

**Comment by Abdelrhman-AK** [comment]
My point of view was to get every scheme was included in Windows. 
If any one used it before in 90s and want to remember these days 😂 then he can reuse it in both Win32UI and color picker in modern Windows elements)

**Comment by OrthodoxWindows** [comment]
In the past, I had made an adaptation of Windows 3.x diagrams for Windows 95+, taking into account the addition of additional 3D parameters. I will try to finish the ports soon. https://winclassic.boards.net/thread/1090/3-nt-colors-schemes

**Comment by Abdelrhman-AK** [comment]
I wish you all the best!
