### ISSUE TITLE
Error with AMOLED 

### ISSUE THREAD

**Issue by bitsuuu** [Abdelrhman-AK/WinPaletter#201]
![image_2023-11-29_212729151](https://github.com/Abdelrhman-AK/WinPaletter/assets/150136356/e11d2639-8eb2-4835-9807-92a2f5f2a14a)
## **Describe the error**
- A short description about error.

## **How to reproduce the error**
- Write here the steps (starting from opening the application) that causes the error.

## **WinPaletter Log**
- If an exception error occurred, press on `copy details` and paste them here. 
- The details will include info about WinPaletter version, date, current OS, exception error message & stack trace.

## **Screenshots/Screen records**
- Don't add screenshot to exception error dialog if you already wrote WinPaletter Log.
- If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
- Add any other context about the problem here.

**Comment by Abdelrhman-AK** [comment]
Log details are not visible completely. Press on this button and then paste it here in a new comment.

![Screenshot_20231129-163642_Chrome.png](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/35544d5d-941d-4c94-bf5b-bd8ac296a211)

**Comment by bitsuuu** [comment]
weird its okay now, maybe because of the update, i dunno what happened, i supposed to give you the log details

**Comment by Abdelrhman-AK** [comment]
No problem, maybe these two bugs that are fixed are the reason:
- Fix issues in Application themer feature
- Fix bug of applying application theme on closing WinPaletter Store with a theme open

Anyway, if you face this issue again, post the details here.
