### ISSUE TITLE
❓ [Question, Support request] The user switch window and the home page also open in CLI mode.

### ISSUE THREAD

**Issue by boromyr** [Abdelrhman-AK/WinPaletter#202]
# **❓ Question or spport request**

## **Describe your question or ask for support\help.**
When I apply a theme with "C:\Program Files\WinPaletter.exe" /apply:D:\Users\PC\Documents\Autohotkey\Ligh.wpth through command line or .lnk, the user switch window pops up every time, starting from 1.0.8.3.
Similarly, when I open a .lnk shortcut with the previous command to change the theme, the main window opens.
My current setting is:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/c77f7339-bfc9-4e54-97d0-31a99d704e60)
but it doesn't seem to work.

---

**Comment by Abdelrhman-AK** [comment]
I'll fix this.

**Comment by boromyr** [comment]
The user switch window no longer appears when a theme is applied, issue resolved.
The main winpaletter window still opens when I apply a theme in silent mode.
![winpaletter](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/cd20f060-e848-489a-be0a-34d8e51bba75)

**Comment by boromyr** [comment]
Resolved, the file existed but the path in the link was incorrect.
