### ISSUE TITLE
❓ [Question, Support request] 

### ISSUE THREAD

**Issue by titusgroen** [Abdelrhman-AK/WinPaletter#204]
# **❓ Question or support request**

## **Describe your question or ask for support\help.**w

---
Can I use this to change how checkboxes appear on windows apps? Right now they are white and when I click on them, it puts a black checkmark in it. But I've seen other people's checkboxes turn blue when checked off and it's just so more easier to read at a glance.

**Comment by Abdelrhman-AK** [comment]
Unfortunately it is not customizable by WinPaletter (till this moment). Only the classic controls (classic buttons, checkboxes, ...) can be cusomized.

Anyway, you can try one of these methods:

- AccentColorizer (search for it in GitHub) but I am not sure if it applies accents on checkboxes or not.

- Try external visual styles (search for them in any search engine online).
