### ISSUE TITLE
the App freezes when i do quick apply on the metrics and fonts window🐞 [Bug] 

### ISSUE THREAD

**Issue by Kinsley12off** [Abdelrhman-AK/WinPaletter#209]
## **Describe the bug**
-When i do an quick apply i freezes with the not responding message in the window title

## **How to reproduce the bug**
- in the metrics and fonts windows on windows 10
- open from default windows
- and click on quick apply

## **Screenshots/Screen records**
![2024-01-16_21h50_45](https://github.com/Abdelrhman-AK/WinPaletter/assets/90274285/272a4ffe-2a2e-4608-8cfa-05f3671fae7f)
After reboot
![2024-01-16_22h00_08](https://github.com/Abdelrhman-AK/WinPaletter/assets/90274285/1e832f12-e341-4dde-8aaa-abaaa26dbbb0)

## **Additional context**
- i was preparing to uninstall the app
- after force closing the app an rebooting the computer it does apply the settings i have set

**Comment by Abdelrhman-AK** [comment]
Check this until I make `Quick apply` applies the aspect in background (separate thread, not UI thread).

https://github.com/Abdelrhman-AK/WinPaletter/wiki/Delay-applying-of-Metrics-and-Fonts

- It is a known issue that may be triggered with multiple applications open.
