### ISSUE TITLE
HotTrackingColor and 3DDarkShadow settings are always the same in each color scheme

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#21]
When navigating between Win32 color schemes, I noticed that the HotTrackingColor and 3DDarkShadow settings are always the same in each color scheme. However, if I click on "Current applied one" or on "Default Windows 10/11" these parameters are correctly modified.

**Comment by Abdelrhman-AK** [comment]
I've just fixed this bug, wait for the next update
