### ISSUE TITLE
Compatibility with Rectify11🚀 [Feature request] 

### ISSUE THREAD

**Issue by Neovolter** [Abdelrhman-AK/WinPaletter#210]
Is it possible to use WinPaletter AMOLED theme with Rectify11 dark theme (where for example a window of Control panel has dark background unlike default W11 where  it is white). I think it would be a nice addition)

**Comment by Abdelrhman-AK** [comment]
It should be possible, but I didn't test it.

**Comment by Abdelrhman-AK** [comment]
- I am doing tests right now after doing some tweaks. Any version from `1.0.8.7` and below may cause conflicts in colors.
- Don't use `1.0.8.7` as it will reset visual styles into Aero (default) not Rectify11's visual styles.
- The next release `1.0.8.8` will partially support Rectify11, there will be some limitations:

 1. Titlebar color will be border color only (and there will be no conflict as the theme is already in black colors).
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/88a31f01-9add-491d-82f9-d1acf031b7ed)

 2. AccentColorizer will take the black color as an accent color, and so Explorer bar and context menu's glyphs will be in black and gray and they are not good at accessibility.
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/cdd16a18-fae0-4203-b2c6-e36ad6a6ef2b)
