### ISSUE TITLE
❓ [Question, Support request] Can I use WinPaletter to completely suppress the Windows logon UI welcome animation?

### ISSUE THREAD

**Issue by jazir555** [Abdelrhman-AK/WinPaletter#211]
# **❓ Question or support request**

## **Describe your question or ask for support\help.**

I want to suppress the windows logon welcome animation and replace it with a black screen so no UI elements display until the default shell loads. Is this possible with WinPaletter?

**Comment by Abdelrhman-AK** [comment]
- Open LogonUI, and disable all toggles then press on 'Load into current theme'
https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-LogonUI-screen#2-contents

- Then open Windows effects, uncheck item 'Animate controls and elements inside window' the  press on 'Load into current theme'
(It will disable some animations including spinning dots in boot screen and LogonUI, it it didn't disable the spinning dots, try disabling other elements in the same section related to animations)

- Finally, apply the theme in the main form.
