### ISSUE TITLE
Can't apply any of the OS theme options (for example Windows 7/8.1) on Windows 10 (Error)

### ISSUE THREAD

**Issue by Jonhhn17818** [Abdelrhman-AK/WinPaletter#212]
I've tried to put the Windows Vista theme on Windows 10, but I can't since it just says that most of the stuff are disabled!

Here's the log it gives me!
[info]	 WinPaletter will apply theme from Windows 10's section

[info]	 20:30:11: Applying started

[apply]	 20:30:11: Saving theme info into registry

[time]	 It took 0,002 seconds

[skip]	 20:30:11: Skipping WinPaletter application theme as it is disabled

[time]	 It took 0,038 seconds

[skip]	 20:30:11: Skipping Wallpaper as it is disabled

[apply]	 20:30:11: Applying Windows 10 scheme

[time]	 It took 0,004 seconds

[apply]	 20:30:11: Applying Windows 10 LogonUI

[time]	 It took 0,002 seconds

[apply]	 20:30:11: Applying Classic Colors

[time]	 It took 0,039 seconds

[apply]	 20:30:11: Applying Windows Effects

[time]	 It took 0,007 seconds

[skip]	 20:30:11: Skipping Windows Metrics and Fonts as they are disabled

[skip]	 20:30:11: Skipping Windows Switcher (Alt+Tab) Appearance as it is disabled

[time]	 It took 0,001 seconds

[apply]	 20:30:11: Applying Wallpaper Tone

[time]	 It took 0,004 seconds

[skip]	 20:30:11: Skipping Command Prompt as it is disabled

[skip]	 20:30:11: Skipping PowerShell x86 as it is disabled

[skip]	 20:30:11: Skipping PowerShell x64 as it is disabled

[skip]	 20:30:11: Skipping Windows Terminal Stable & Preview as they are disabled

[apply]	 20:30:11: Applying Screen Saver

[time]	 It took 0,002 seconds

[apply]	 20:30:11: Applying Sounds

[time]	 It took 0,22 seconds

[info]	 20:30:11: Saving Windows Cursors Colors to registry

[time]	 It took 0,014 seconds

[apply]	 20:30:11: Rendering Windows Cursors

[time]	 It took 0,154 seconds

[apply]	 20:30:11: Applying Windows Cursors

[time]	 It took 0,023 seconds

[time]	 Total applying Windows cursors took 0,204 seconds

[success]	 20:30:11: Applying theme done. It took 0,601 seconds

[info]	 20:30:11: All operations are done

I did  also did the thing which removes the Microsoft Defender detection and still nothing changed!

**Comment by Abdelrhman-AK** [comment]
Open each Windows aspect and make the toggles enabled then press on 'Load into current preferences', and re-apply the theme and finally tell me if it worked.

**Comment by Jonhhn17818** [comment]
Sadly it didn't. Still experiencing the same errors.

**Comment by Abdelrhman-AK** [comment]
### Do you use 1.0.8.5 or a lower version?

### - If it is 1.0.8.5, make sure that the new feature (Aspects control) is disabled in settings like this screenshot:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/9f71e778-a539-46dd-83fd-907951ed09ad)

### - If it is a lower version, close WinPaletter, delete this registry key and then reopen WinPaletter:
`HKEY_CURRENT_USER\Software\WinPaletter`

**Comment by chaosxeloc** [comment]
I have the same issue. Trying to apply Windows Switcher changes after downloading WinPaletter today, but it says it's disabled along with most (if not all) of the other features. Deleting the registry key and starting over didn't seem to change anything.

**Comment by Abdelrhman-AK** [comment]
- Does version `1.0.8.4` have the same issue? If not, I'll remove Aspects control feature.
- Do you have multiple users account on Windows?
- I'll try to do adjustments in applying process.

**Comment by Abdelrhman-AK** [comment]
@Jonhhn17818 I misunderstood you before.

It's not feasible to apply Windows 7/8.1 themes on Windows 10. I've developed an OS switch feature in WinPaletter, allowing users to create a single theme file that's compatible across various operating systems, from Windows XP to 11. When switching the OS in WinPaletter, the preview changes accordingly, enabling users to visualize how their theme file would appear on different operating systems.

When applying a theme file in Windows 11, it will implement the colors and theme specific to Windows 11. Similarly, if you're using Windows 7, it will adopt the theme elements pertinent to Windows 7, and the same principle applies to other operating systems accordingly.

**Comment by chaosxeloc** [comment]
After some rest I realized that there may have been a conflict with another program I have used for years called `Display Fusion`. I have never used it for Alt+Tab functionality, but it apparently has options that conflicted with WinPaletter in this instance. Completely user error on my part.

Regardless, I have exported the registry below using version `1.0.8.7`. I currently only have one user account on Windows.

[WinPaletterExport.txt](https://github.com/Abdelrhman-AK/WinPaletter/files/14618825/WinPaletterExport.txt)

**Comment by Abdelrhman-AK** [comment]
I have used your preferences after importing registry, and couldn't reproduce this issue. There is another issue that is simmilar to this and I can't reproduce it too: https://github.com/Abdelrhman-AK/WinPaletter/issues/218#issuecomment-1982191958

Try using WinPaletter `1.0.8.4` and let me know if it worked right or not, so I'll revert back "Aspects Control" feature.

**Comment by Abdelrhman-AK** [comment]
I tried to reproduce this issue after importing your registry, enabled all aspects toggles (except for Windows Terminal Stable 🔴 ), and found some aspects skipped:

```
[info]	 WinPaletter will apply theme from Windows 11's section
[info]	 10:47:49 PM: Applying started
[apply]	 10:47:49 PM: Saving theme info into registry
[time]	 It took 0.011 seconds
[skip]	 10:47:49 PM: Skipping WinPaletter application theme as it is disabled ◀️ ◀️ ◀️ ◀️ ◀️ ◀️ 
[time]	 It took 0.069 seconds
[apply]	 10:47:49 PM: Applying Wallpaper
[time]	 It took 0.009 seconds
[apply]	 10:47:49 PM: Applying Windows 11 scheme
[time]	 It took 0.241 seconds
[apply]	 10:47:49 PM: Applying Windows 11 LogonUI
[time]	 It took 0.01 seconds
[apply]	 10:47:49 PM: Applying Classic Colors
[time]	 It took 0.101 seconds
[apply]	 10:47:49 PM: Applying Windows Effects
[time]	 It took 0.01 seconds
[apply]	 10:47:49 PM: Applying Windows Metrics and Fonts
[time]	 They took 0.009 seconds
[skip]	 10:47:49 PM: Skipping Windows Switcher (Alt+Tab) Appearance as it is disabled ◀️ ◀️ ◀️ ◀️ ◀️ ◀️ 
[time]	 It took 0.009 seconds
[apply]	 10:47:49 PM: Applying Wallpaper Tone
[time]	 It took 0.026 seconds
[apply]	 10:47:50 PM: Applying Command Prompt
[time]	 It took 0.025 seconds
[apply]	 10:47:50 PM: Applying PowerShell x86
[time]	 It took 0.019 seconds
[apply]	 10:47:50 PM: Applying PowerShell x64
[time]	 It took 0.018 seconds
[skip]	 10:47:50 PM: Skipping Windows Terminal Stable as it is disabled 🔴
[info]	 10:47:50 PM: Checking if Windows Terminal Preview is installed
[info]	 10:47:50 PM: Applying Windows Terminal Preview
[time]	 It took 0.235 seconds
[apply]	 10:47:50 PM: Applying Screen Saver
[time]	 It took 0.015 seconds
[apply]	 10:47:50 PM: Applying Sounds
[time]	 It took 0.537 seconds
[info]	 10:47:50 PM: Saving Windows Cursors Colors to registry
[time]	 It took 0.049 seconds
[apply]	 10:47:51 PM: Rendering Windows Cursors
[time]	 It took 0.339 seconds
[apply]	 10:47:51 PM: Applying Windows Cursors
[time]	 It took 0.075 seconds
[time]	 Total applying Windows cursors took 0.523 seconds
[success]	 10:47:51 PM: Applying theme done. It took 2.139 seconds
[info]	 10:47:51 PM: All operations are done
```

There is another issue that is simmilar to this (for Metrics and Fonts only) and I can't reproduce it too: https://github.com/Abdelrhman-AK/WinPaletter/issues/218#issuecomment-1982191958

If these are the aspects not being applied for you, let me know and I'll fix it.

If not, try using WinPaletter `1.0.8.4` and let me know if it worked right or not, so I'll revert back "Aspects Control" feature.

**Comment by chaosxeloc** [comment]
My apologies, I wasn't exceptionally clear in my last post. Both WinPaletter `1.0.8.4` and `1.0.8.7` work as intended after I disable the conflicting program, `Display Fusion`. Effects such as Alt+Tab Appearance work as intended. I simply failed to heed the warning about potential third-party program conflicts.

**Comment by Abdelrhman-AK** [comment]
No problem! I am fixing now small issues in applying process.

**Comment by Abdelrhman-AK** [comment]
I'll add a warning at WinPaletter startup about potential third-party program conflicts too, as another issue happened before due to a conflict with ExplorerPatcher.
