### ISSUE TITLE
🐞 [Bug] Closing the main tab in winpaletter while leaving other tabs opened shall not be allowed! 

### ISSUE THREAD

**Issue by sudo-000** [Abdelrhman-AK/WinPaletter#214]
## 🐞 Bug report

If the user open another tab, then click close on the main tab, then click 'NO'. They can no longer go back to the main tab without restarting the app. Furthermore, they can continue to close all other tabs and resulting in a completely blank WinPaletter window. 

Version: 1.0.8.5-beta

**Comment by Abdelrhman-AK** [comment]
I'll fix this.
