### ISSUE TITLE
It's a bit dangerous, isn't it?

### ISSUE THREAD

**Issue by NoNameNeeded5** [Abdelrhman-AK/WinPaletter#217]
# **❓ Question or spport request**

## **Describe your question or ask for support\help.**

---All I wanted to do is to save and apply Windows themes.

Instead, WinPaletter messed with Explorer Patcher settings, altered the login screen and entirely removed sleep mode from Windows.

So I'm not sure if that is a very good program.

(and no, I certainly didn't change any settings that would do that (why would I?)

So maybe you should think about another hobby, programming isn't really your thing as it seems.

Sorry if this sounds a little harsh but I'm a little furious because I spend the last few hours repairing Windows because WinPaletter totally screwed everything up.

**Comment by Abdelrhman-AK** [comment]
> So I'm not sure if that is a very good program.
> (and no, I certainly didn't change any settings that would do that (why would I?)
> So maybe you should think about another hobby, programming isn't really your thing as it seems.

You could have asked me for help in fixing these issues or even used the theme backup feature that I just created in the last update, instead of using inappropriate talk.

Programming is not a monopoly. I love it and won't change my mind, and I admitt that I am not professional or expert. You can make me better if you have told me about these issues and I for sure I will be better and better (and anyone will be so), and for sure will fix this app if it already had issues.

> ---All I wanted to do is to save and apply Windows themes.

You must have used a theme from the store, which will override current preferences.

> WinPaletter messed with Explorer Patcher settings

There are common elements in Windows Effects and ExplorerPatcher, including the command bar. You could have disabled the Windows Effects toggle to ensure that WinPaletter doesn't apply it. Additionally, you can open Settings > Aspects control, enable the toggle, and uncheck the items you want to be skipped.

> altered the login screen.

There are only 3 modifiable elements that can be reverted !!!! and also you can disable its controlling (secure) toggle

> and entirely removed sleep mode from Windows.

There is no SINGLE CODE in WinPaletter that does that !!!

**Comment by NoNameNeeded5** [comment]
First of all, I didn't want to sound as unfriendly as it probably sounded, so apologies for that.

But secondly,I'm still not a fan of your tool.

All of the harmless things (like changing wallpapers, changing cursors) are disabled by default.

However, the things that can't be undone easily by the user are enabled by default.

So by saving a theme (just the standard settings as I had them, wallpaper, cursor and everything) and applying it again, I inadvertently changed settings that I never intended to change.
Like the login screen or Explorer Patcher settings.

Explorer Patcher was so totally screwed up, I couldn't even get to the settings window (error message). The taskbar wasn't usable at all.
I finally was able to reinstall Explorer Patcher and get it working again.

However, the rotating circle is still missing from the login screen, I still wasn't able to solve that problem.
(even though WinPaletter doesn't even offer the option to remove it, that was exactly what it did)

And about sleep mode: I have absolutely no idea how WinPaletter managed to disable that. All I know is that it did. I certainly wouldn't know how to do that.
I had to search the internet for hours to get it working again.

But anyway, please disable all the options by default that the average user cannot easily set back to its former settings. Enable the harmless options instead and if somebody dares to change other things they can manually enable them.

**Comment by Abdelrhman-AK** [comment]
I have understood the issue now. All screwed up things are in one section, that is Windows Effects. There is no issue in Lock screen spinning dots.

Open Windows Effects, enable this option: 'Animate controls and elements inside windows' and apply this section only, disable the toggle and re-press on apply and finally restart your Windows.

> But anyway, please disable all the options by default that the average user cannot easily set back to its former settings. Enable the harmless options instead and if somebody dares to change other things they can manually enable them.

I will make Windows Effects disabled by defaults, and will try to implement a method to block harmful options for users. If they want to edit them then they should unblock the options in settings.

> And about sleep mode: I have absolutely no idea how WinPaletter managed to disable that. All I know is that it did. I certainly wouldn't know how to do that.
I had to search the internet for hours to get it working again.

Can you tell me the method of fixing it or a URL, so I can understand that issue and know if WinPaletter is related to this issue or not?

**Comment by NoNameNeeded5** [comment]
To be honest, I don't dare to launch your program again.
(I tried it in a virtual machine to see if I could reproduce the problem with the removed sleep mode but it wouldn't open).

Do you mean this setting?

https://www.tenforums.com/tutorials/126844-enable-disable-animate-controls-elements-inside-windows.html

If so, that's not enough.
That setting will enable the rotating circle when you shut down or restart Windows, however it will not bring back the rotating circle on the login screen (which is the one that's still missing).

So when I tried to find a solution I found a comment in a thread somewhere which claimed, that the missing circle might have something to do with faulty power options so that's when I checked the power options and that's how I found out that the sleep mode option was simply gone.

I don't know exactly how I was able to get back the sleep mode because I've tried many different solutions until I finally found one that worked.

I tried options 3 and 4:
https://www.makeuseof.com/windows-10-fix-mising-sleep-option/

One of them might have worked or it was something else.

**Comment by Abdelrhman-AK** [comment]
> I tried options 3 and 4:
https://www.makeuseof.com/windows-10-fix-mising-sleep-option/

I have just read this URL. This issue is not related to WinPaletter at all. There is no registry modification implemented in this app that manipulates power modes or even hides sleep mode.

**Comment by NoNameNeeded5** [comment]
All I can tell you is that it happened when I used your program.

Also the thing with the missing rotating circle points in that direction, because the missing rotating circle seems to be related to the power options (although I don't know why and how).

**Comment by Abdelrhman-AK** [comment]
I don't know which power option should control this too.

I have read this in a thread, you can try it and I am not sure if it should work for you: 

> Did NOT fix the problem.. no spinning dots on ‘Please Wait’ screen or Login screen. Only the restart screen had the spinning dots.
> This fixed the problem:
> In HKEY_USERS.DEFAULT\Control Panel\Desktop\ there’s a binary called UserPreferencesMask: the fifth value shall be 12 instead of 10 for the animations to work in common areas.

**Comment by NoNameNeeded5** [comment]
I don't know it either.

And unfortunately the registry settings didn't work.

**Comment by NoNameNeeded5** [comment]
Ok, now it did finally work.

So thx for the hint.

Now, after a few hours everything seems to be ok again.

But it wasn't too much fun.

So as I said, please disable all the stuff that might do harm to the users' computer by default.

**Comment by Abdelrhman-AK** [comment]
OK. I will disable Windows Effects by default in the next update.

And in the near future, I will try to implement a method to block harmful options (and they can be unblocked in settings)

Finally, I am sorry for this mess and disturbance.
