### ISSUE TITLE
Possible to run .\WinPaletter.exe --apply with SILENT parameter?

### ISSUE THREAD

**Issue by MaartenMol** [Abdelrhman-AK/WinPaletter#219]
# **❓ Question or spport request**

## **Describe your question or ask for support\help.**
I am running .\WinPaletter.exe --apply .\wallpaper.wpth to apply a wallpaper. I would love it to make this silent. Is it possible? When I run it now I am always getting prompted about effects?
![afbeelding](https://github.com/Abdelrhman-AK/WinPaletter/assets/12127047/ddb485d2-fd11-4294-8c25-289dd103fa9d)
---

**Comment by Abdelrhman-AK** [comment]
It is possible for sure, but there are massive issues reported by someone in #217 (you can read it) and they are all resulted from modifying some ExplorerPatcher options that share with Windows Effects in WinPaletter and modifying user preference mask (UPM) in Windows Registry.

I'll replace it with a dialog that has a choice for not showing this dialog again.
