### ISSUE TITLE
Feature Requests : Support for "Flat Menus" and "Gradient Titlebar" options without logging off.

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#22]
I think (I'm not very experienced in programming, so I'm not sure), the function is quite similar to Win32 colors (GetSysColor), it's SystemParametersInfoA (https://docs.microsoft.com /en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa). More precisely, I found SPI_GETFLATMENU 0x1022/
SPI_SETFLATMENU 0x1023 and SPI_GETGRADIENTCAPTIONS 0x1008/SPI_SETGRADIENTCAPTIONS 0x1009

**Comment by Abdelrhman-AK** [comment]
I managed to do this right now. It will be available in the next update..
Thanks !!
