### ISSUE TITLE
Change the color of Quick Access links

### ISSUE THREAD

**Issue by linguaccia22** [Abdelrhman-AK/WinPaletter#222]
Hi, but is it possible to change the color of the writing on the quick access link icons?
I also wanted to ask if it was possible to change the color of the titles of all the folders.

I use a theme with transparent folders and with the background you can't see the writing of the folder and the links in the quick access panel well. I wanted to understand if using this problem I could customize all the fonts on a transparent folder.

Thank you

**Comment by Abdelrhman-AK** [comment]
I don't know if this will be possible with your visual styles or not, but you can try Classic Colors in WinPaletter.

Try to modify Window Text and Selection objects:

https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-classic-colors#3-selection-objects

https://github.com/Abdelrhman-AK/WinPaletter/wiki/Edit-Windows-classic-colors#4-windows-objects

**Comment by Abdelrhman-AK** [comment]
They are not possible by modifying registry, try using a custom visual styles. Search for them online and use SecureUxTheme to apply it.
