### ISSUE TITLE
[Beta] The command line application changes the title bar.

### ISSUE THREAD

**Issue by boromyr** [Abdelrhman-AK/WinPaletter#225]
## **Describe the error**
Applying the WP theme from the command line, the title bar buttons are altered, switching from those of the currently applied msstyle theme to the default Windows ones, while applying the theme from the GUI this does not happen.

## **How to reproduce the error**
- Apply a third-party msstyle theme with a different title bar style than the standard Windows one.

## **Screenshots/Screen records**
![2](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/735724f4-7abe-48f6-8fce-0623f4889faa)

## **Additional context**
- Windows 11
- [UX patch](https://mhoefs.eu/software_uxtheme.php?lang=en)
- WP 1.0.8.8 beta

**Comment by boromyr** [comment]
I also noticed that when 
```json
  "Windows11": {
    "Enabled": false,
```
the problem does not occur.
I don't know if you are familiar with https://github.com/namazso/SecureUxTheme, but it could be a great addition or solution for managing msstyle themes. It doesn't require modifications to system files, just registering a dll, and it could allow Windows to directly manage themes, compatible with third-party themes as well.

**Comment by Abdelrhman-AK** [comment]
The actual cause of the issue is the `Theme` entry:

```json
  "Windows11": {
    "Enabled": true,
    "Theme": 0,
```
- When `"Enabled": false`, nothing in Windows 11 colors wil be done.

- I have made a code tweak for #210 in version `1.0.8.8` to make WinPaletter use the visual styles loaded at app startup when `"Theme": 0`, and AeroLite when `"Theme": 1`.

- I can create another value for `Theme` to prevent WinPaletter from editing the current visual styles.

- If you have multiple users, the command prompt method may have an issue with retrieving the current user (since the command line attempts to apply the theme as silently as possible). I'll redo some tests.

---

> I'm not sure if you're familiar with https://github.com/namazso/SecureUxTheme, but it could be a great addition or solution for managing msstyle themes. It doesn't require modifications to system files; you simply need to register a DLL, and it could allow WP to directly manage themes, compatible with third-party themes as well.

- I am familiar with this app, but unfortunately, I don't know how to patch UxTheme.dll as I have no experience with it. If I learn how to do this, I'll be able to register it and certainly be able to create a new aspect for managing visual styles.

- And another reason, and I'm sorry to say it, there is a great possibility that I won't be able to develop WinPaletter anymore after a few weeks (after I release a stable version `1.0.9.x`). I won't have any time for it. I'll provide further details later in `readme.md`

- I might quickly create an aspect that manages visual styles provided that `UxTheme.dll` is patched. If I succeed at this, I'll implement this feature. I'll do some tests.

**Comment by Abdelrhman-AK** [comment]
I have just found it.

``` cs
FirstVisualStyles = UxTheme.GetCurrentVS().Item1 ?? SysPaths.Windows + "\\Resources\\Themes\\aero\\aero.msstyles";
```

- I used this in #210 situation, It is execuded after commands lines parsing, and so the issue occured.
- I have moved it before executing commands lines.

**Comment by boromyr** [comment]
Should I compile the latest commit and test it? Yes, `"Enabled": false` was only used to isolate the issue and simplify the tests.

No need to patch any files, just register SecureUxTheme.dll, then you can apply the theme you want through the GUI or through the ThemeUI.dll library https://github.com/namazso/SecureUxTheme/issues/120, it is also used by Rectify11.

**Comment by Abdelrhman-AK** [comment]
> Should I compile the latest commit and test it? Yes, `"Enabled": false` was only used to isolate the issue and simplify the tests.
> 

Yes, you can compile and test it.

> No need to patch any files, just register SecureUxTheme.dll, then you can apply the theme you want through the GUI or through the ThemeUI.dll library https://github.com/namazso/SecureUxTheme/issues/120, it is also used by Rectify11.

I'll try implementing it.

**Comment by boromyr** [comment]
I can no longer compile WP, I manually downloaded the missing NuGet packages:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/d90543e3-ed6b-4f9a-a8b5-37dff492f7c3)
but imageprocessor, even if installed, is not recognized, and devcorp cannot be found in the NuGet search.
If you have the compiled file, can you upload it? Let's do it faster.

**Comment by Abdelrhman-AK** [comment]
https://github.com/Abdelrhman-AK/WinPaletter/blob/master/WinPaletter%2FResources%2FAssemblies.zip

Assemblies are zipped and added into apps's resources, and when an assembly is required, WinPaletter opens this zip into memory, loads it and finally closes the zip memory stream.

### Load missing assemblies and make them not copied into the local directory if you want.

**Comment by Abdelrhman-AK** [comment]
I was about to push a new update today, but I will wait for you to test it.

**Comment by boromyr** [comment]
Where should I extract them exactly so that they are detected by VS? If you have WinPaletter.exe ready, I can try that directly.

**Comment by Abdelrhman-AK** [comment]
Anywhere you like, remove the missing assmebly then readd it from the directory into which you've extracted.

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/379be94d-a7d6-4c2d-80e5-f0ddddee2b0e)

**Comment by boromyr** [comment]
Ok, filled out. I'll do some tests and let you know

**Comment by boromyr** [comment]
From the GUI I can apply the theme without any problem, through the CLI I get the error:
```cs
//General information
//...........................................................
   Report.Date = "martedì 26 marzo 2024 00:04:30";
   OS = "Windows 11, 10.0.22635.3350, 64-bit";
   WinPaletter.Version = "1.0.8.9, Beta, Build: Release";
   WinPaletter.Language = "English";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "Object reference not set to an instance of an object.";
   Exception.type = "System.NullReferenceException";
   Exception.stack.trace =
   {
      at WinPaletter.Theme.Structures.Win32UI.Apply(TreeView treeView)
      at WinPaletter.Theme.Manager.<>c__DisplayClass0_1.<Save>b__24()
      at WinPaletter.Theme.Manager.Execute(MethodInvoker method, TreeView treeView, String statingStr, String errorStr, String TimeStr, Stopwatch overallStopwatch, Boolean skip, String skipStr)
   };
   Exception.target.void_function = "WinPaletter.Apply()";
   Exception.assembly = "WinPaletter, Version=1.0.8.9, Culture=neutral, PublicKeyToken=null";
   Exception.assembly.file = "C:\\Program Files\\WinPaletter.exe";
   Exception.HRESULT = -2147467261;
```

**Comment by Abdelrhman-AK** [comment]
In Solution explorer: `WinPaletter > Theme > Structures > Windows Colors > Win32UI.cs`

Line: 364

```
                    case WindowStyle.W11:
                        _vs = Program.TM.VisualStyles_11; <---------------------
                        break;
```

I'll work on it right now, and tell you what I did.

**Comment by Abdelrhman-AK** [comment]
In Solution explorer: `WinPaletter > Program > Arguments.cs`
at void `ExecuteArgs()`

```cs
if (o.Apply != null)
{
    if (System.IO.File.Exists(o.Apply))
    {
        using (Theme.Manager TMx = new(Theme.Manager.Source.File, o.Apply, false, o.SilentApply))
        {
            Forms.Home.Text = System.IO.Path.GetFileName(o.Apply);
            Program.TM = TMx.Clone() as Theme.Manager; // <------ new line
            TMx.Save(Theme.Manager.Source.Registry, string.Empty, null, false, o.SilentApply);
            if (Settings.ThemeApplyingBehavior.AutoRestartExplorer) RestartExplorer();
            Program.TM = Program.TM_Original.Clone() as Theme.Manager; // <------ new line

            ExternalLink = true;
            ExternalLink_File = o.Apply;
        }
    }

    shouldExit = true;
}
```
The new two lines fixed the issue

**Comment by boromyr** [comment]
Ok, it works. I also tried enabling the msstyle theme with the new secureuxtheme integration and it didn't cause any issues. Now I will try uninstalling ultrauxtheme and see if the theme change works correctly with secureuxtheme.

How can I disable this window?
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/91ad1053-1b44-4873-bc32-8be29e2691bf)

**Comment by Abdelrhman-AK** [comment]
Is this the first time for this dialog to appear?

**Comment by boromyr** [comment]
It has always appeared to me since 1.0.8.4, or earlier...

**Comment by Abdelrhman-AK** [comment]
I made this appears everytime you open WinPaletter if there are multiple users. WinPaletter will work on the scope of the selected user.

**Comment by boromyr** [comment]
I have only one user on the computer, I don't know who the other one is.

>I can make a choice to automatically select the user who opened WinPaletter, if you want this.
Surely it would be more convenient, even for other users.

**Comment by Abdelrhman-AK** [comment]
It must be from a service you have installed by another program.

We will try to change its type from Local User to System Profile.

In command prompt, type `NET USER` and give me the output.

**Comment by boromyr** [comment]
Maybe it depends on the disabled UAC?
```

Account utente per \\PC

-------------------------------------------------------------------------------
Administrator            DefaultAccount           Guest
PC                       WDAGUtilityAccount
Esecuzione comando riuscita.
```

**Comment by Abdelrhman-AK** [comment]
No. I have tested it without UAC. It is not the cause.

What about using 'netplwiz'?

**Comment by boromyr** [comment]
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/46c89203-c7b5-4f7c-98af-fc0091a910b9)
Maybe it could be a residual account from some test that you don't remember or from the online account? I will also search in the system registry, maybe I could find something.

**Comment by Abdelrhman-AK** [comment]
They are not residuals, I have actually tested them dozens of times in my real PC and Virtual Machines.

I have noticed that this user account PC's name is NT Service and is different from your PC's name. I can make this account hidden among the system profiles in WinPaletter.

I'll provide you with codes updates when I finish.

**Comment by boromyr** [comment]
Ok thank you, here are the results if they can be helpful to you
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/52782032/3dee1705-d2f5-47c5-b4fd-ad06a567bc3c)

**Comment by Abdelrhman-AK** [comment]
Thanks for this screenshot, we won't manipulate this account.

I'll make it hidden.

**Comment by Abdelrhman-AK** [comment]
In Solution explorer: `WinPaletter > Program > Users > Users.cs`
In `public static Dictionary<string, string> GetUsers(bool includeSystemProfiles = false)`

in loop `foreach (string sid in FoundSIDs)` you will find a bool called `condition_base`

```cs
bool condition_base = includeSystemProfiles | !username.ToUpper().StartsWith("NT AUTHORITY", StringComparison.OrdinalIgnoreCase);
```

update it by

```cs
bool condition_base = includeSystemProfiles | !(username.ToUpper().StartsWith("NT AUTHORITY", StringComparison.OrdinalIgnoreCase) && !username.ToUpper().StartsWith("NT SERVICE", StringComparison.OrdinalIgnoreCase));
```

Test it and tell me.

**Comment by boromyr** [comment]
Unfortunately, nothing changes, maybe instead of using StartsWith() there is a method contains to check if "NT" is contained?

**Comment by Abdelrhman-AK** [comment]
If someone called his PC `NT 012` for example, WinPaletter will deal with this user as a system user, not a regular one.

```cs
string username = new SecurityIdentifier(sid).Translate(typeof(NTAccount)).ToString();
MsgBox(username);
```

When the NT Service we want appers in the message box, press on `Ctrl+C` to copy message box content and paste it here.

**Comment by boromyr** [comment]
[Window Title]
WinPaletter

[Main Instruction]
NT SERVICE\lkClassAds

I have therefore tried without success.
```cs
bool condition_base = includeSystemProfiles | !(username.ToUpper().StartsWith("NT AUTHORITY", StringComparison.OrdinalIgnoreCase) && !username.ToUpper().StartsWith("NT SERVICE\\lkClassAds", StringComparison.OrdinalIgnoreCase));
```

**Comment by Abdelrhman-AK** [comment]
My bad !!!
```cs
bool condition_base = includeSystemProfiles | !(username.ToUpper().StartsWith("NT AUTHORITY", StringComparison.OrdinalIgnoreCase) !! username.ToUpper().StartsWith("NT SERVICE", StringComparison.OrdinalIgnoreCase));
```

**Comment by boromyr** [comment]
ah see, it was an OR, I didn't notice it either, now it works!!!!

**Comment by boromyr** [comment]
Furthermore, the msstyle theme change also works without a patched uxtheme.

**Comment by Abdelrhman-AK** [comment]
How is this?
- I tested it before patching and didn't work for me. Maybe there is something from uxthemepatcher you tried before SecureUxTheme.
- Try a Windows restart and see if visual styles resets to aero or not.

**Comment by boromyr** [comment]
Sorry, what do you mean? Maybe I expressed myself poorly, I meant that WP now correctly changes the msstyle theme with the new secureuxtheme integration. I uninstalled uxthemepatcher last night to avoid false positives, and to verify that WP was actually using SecureUxTheme, and it works fine.

**Comment by Abdelrhman-AK** [comment]
Great. I've understood you.
