### ISSUE TITLE
Scale option for cursor (increase cursor size).

### ISSUE THREAD

**Issue by yugo2911** [Abdelrhman-AK/WinPaletter#227]
## **Is your Enhancement request related to a problem? Please describe.**
-Scale option for cursor (increase cursor size).
---

### **Additional context**
Cursor customization is very good, just feels unfortunate that I can't make my cursor larger size.
---

**Comment by Abdelrhman-AK** [comment]
As I don't have time, I won't be able to implement it as a feature. I promise that if I have time and work on version 1.0.9.1, I'll implement it. 

Anyway, you can do this manually. Open Registry Editor, go to `HKEY_CURRENT_USER\Control Panel\Cursors` and set values for `CursorBaseSize` in Decimal base to `32`, `48`, or `64`, and so on. Finally, log off and log on.

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/afce5d3b-2aa2-40f0-bedc-e92f7b6d6e8c)

**Comment by yugo2911** [comment]
Thanks!
Everything works and looks pretty now :)

**Comment by Abdelrhman-AK** [comment]
You're welcome!
