### ISSUE TITLE
Previewer: in active window title the font is usually bold

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#24]
In default Windows schemes, the font in the active title is bold. This is configurable but in Win Standard scheme and others it is the case.

**Comment by Abdelrhman-AK** [comment]
![4444](https://user-images.githubusercontent.com/59510211/184973303-e03c375f-5a83-4704-929c-5e672814b1e7.jpg)

The classic mode I used (Simple Classic theme) in Windows 10 didn't make the active titlebars bold, but Windows XP and 7 showed it bold.
So I'm confused if I make it bold or normal 😂

**Comment by Anixx** [comment]
The font style is part of the color scheme and is not depended on the method of disabling theming. It can be bold or not, but in Windows 2000 and Windows 95 schemes it is bold.
![изображение](https://user-images.githubusercontent.com/1271736/184987504-aa2d5028-4dea-48ed-ad24-ea003ed32527.png)

**Comment by Abdelrhman-AK** [comment]
Ok, very nice. 
I'll make it detect from Windows Metrics if its font is bold or not

**Comment by Anixx** [comment]
It also can be Italic (the next button)

**Comment by Abdelrhman-AK** [comment]
- Yup, I have used the LOGFONTA module to convert bytes of registry into font info .. I will implement both font weight (Regular/Bold) and "LFItalic"

- Getting font size from Byte() is kind of complicated and I can't find a method to get it from WindowsMetrics, so I used Segoe UI and Size 9. Font Style is from "LFWeight"

_https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfonta_
