### ISSUE TITLE
Win32 UI previewer : The ClientEdge bottom line is invariable when changing color scheme.

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#26]
This is the line normally supported by 3D-DarkShadow. When manually changing the 3D-DarkShadow parameter, the line (botton ClientEdge line) is displayed correctly.

Here is the line : 

![WinPaletter_AXy1skNBPc](https://user-images.githubusercontent.com/100134023/184915471-e2b37737-398d-4618-90bc-2a188ab64479.png)

**Comment by Abdelrhman-AK** [comment]
I'll fix it. Thanks!
