### ISSUE TITLE
Win32UI previewer: Missing third bar in 3D menus (with flat menus disabled).

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#27]
The 3D menus are displayed perfectly in the previewer, except for an interior bar which does not display at all. This is a bar with the same colors on each side; this color is that of the 3D-Face setting.

![vq7UgoDMAn](https://user-images.githubusercontent.com/100134023/184918141-3a7490cc-3fa6-45a1-be58-b296508742ef.png)

In the picture it is the light gray line.
This issue is my fault, I forgot to tell you this in the past.

**Comment by Abdelrhman-AK** [comment]
I don't think this classic mode is right, as Windows 98, Windows XP (Classic) and Windows 10 (Classic) showed me the same pattern of lines in the attached screenshot. The mistake here is the superior and left line migrated to the top, left by one pixel. 

- If you could double check with another mode\patch or another theme, it would be very nice of you.

![4444](https://user-images.githubusercontent.com/59510211/184971278-600c2a65-887d-4247-a49c-d577a5ebfb2a.jpg)

**Comment by Abdelrhman-AK** [comment]
Another Screenshot with different colors
![Untitled](https://user-images.githubusercontent.com/59510211/184977395-7e3e863d-7060-43b1-a9d2-81dae6c69eb2.png)

**Comment by OrthodoxWindows** [comment]
For most color schemes rendering is perfect, but not for schemes where menu setting colors are different from 3D-Face setting (for example, most Windows 3.x color schemes). Of course, if the two colors (3D-Face and Menu) are similar, the menu is displayed correctly.

**Comment by Abdelrhman-AK** [comment]
I have noticed that!! I'll fix it. Thank you
