### ISSUE TITLE
Feature request : ExplorerPatcher support

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#28]
ExplorerPatcher is a personalization program for Windows 10 and Windows 11 that restores many Windows 10 user interface elements in Windows 11, including the taskbar, start menu, and system tray flyouts (wifi networks, clock, sound, battery and language bar). It also disables rounded corners (however, it cannot restore Windows 10 notification center). My suggestion is therefore to take into account the parameters in question in the accent color previewer, and in the accent color picker (ie, adapt the terms used according to the parameters activated in ExplorerPatcher).
I don't have Windows 11, so I can't test. It is however possible that I install it in a virtual machine in the future. Here is the ExplorerPatcher documentation : https://github.com/valinet/ExplorerPatcher/wiki/All-features
The developer has closed the discussion area, but it is possible to contact him on this thread : https://www.elevenforum.com/t/new-version-of-explorerpatcher.1991/page-43

**Comment by Abdelrhman-AK** [comment]
Do you mean (for example) when Action Center of Windows 10 is enabled in Windows 11, the previewer shows Action Center of 10 not 11, and so on ..... ?

**Comment by Abdelrhman-AK** [comment]
I may work on this later on, not now.

As I'm working on some features (Extended support to Window 7 and 8.1, Right-Click menus on colors to ease managing the palette).
And I'm coding for one-two hours a day as I'm studying 😂. Once I finish these, I'll work on ExplorerPatcher.

**Comment by Abdelrhman-AK** [comment]
Huge thanks bro!

**Comment by Anixx** [comment]
> I don't have Windows 11, so I can't test. 

EP can run on Win10 as well (starting from certain build)

**Comment by Anixx** [comment]
> It also disables rounded corners 

As I can tell, it uses rather a cumbersome method, loading a resident module into DWM... very complicated.

**Comment by OrthodoxWindows** [comment]
> > I don't have Windows 11, so I can't test.
> 
> EP can run on Win10 as well (starting from certain build)

I'm using ExplorerPatcher on Windows 10, but I can't test Windows 11-specific features.

**Comment by OrthodoxWindows** [comment]
> > It also disables rounded corners
> 
> As I can tell, it uses rather a cumbersome method, loading a resident process... very complicated.

I think a proper detection method would just be to detect if the "disable rounded corners" setting is active or not (maybe via registry).

**Comment by Abdelrhman-AK** [comment]
> I think a proper detection method would just be to detect if the "disable rounded corners" setting is active or not (maybe via registry).

Exactly, the best way is getting it from registry or config file, instead of complex method of DWM.
