### ISSUE TITLE
Win32UI : Problem with selected button in the previewer.

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#30]
In the previewer, the selected button uses the 3D-DarkShadow color, when it should use the WindowFrame color. Also, WindowFrame's color is named _FrameButton (After Click)_ when it should be named _FrameButton (Selected and After Click)_, since the border of the selected button uses the WindowFrame color.

Previewer :
![WinPaletter_0JOek4AINh](https://user-images.githubusercontent.com/100134023/187089597-72312d21-c255-4d03-bc52-ad91c96b1037.png)

System:
![explorer_gcQj2rG3yz](https://user-images.githubusercontent.com/100134023/187089620-76350f19-a367-455c-8349-c8c087080120.png)

In both cases, the selected button is the OK button.

**Comment by Abdelrhman-AK** [comment]
I'll fix that.
