### ISSUE TITLE
Cursor theme

### ISSUE THREAD

**Issue by MNSBKillJoy** [Abdelrhman-AK/WinPaletter#31]
Cursor colors not taking effect, despite enabling the toggle and activating automatic apply custom cursors in settings
![Skærmbillede 2022-09-05 002007](https://user-images.githubusercontent.com/112830724/188335620-25623b93-11a9-4f03-9221-670396612308.png)
![Skærmbillede 2022-09-05 002037](https://user-images.githubusercontent.com/112830724/188335622-98cf6739-d4ec-44aa-be33-3ae7eac21289.png)

**Comment by Abdelrhman-AK** [comment]
Do you use a 32-bit OS ?

I have found a bug happens when you use an OS 32-bit and I have fixed it.. wait for next update (very soon)

**Comment by MNSBKillJoy** [comment]
I'm using a 64-bit, windows 11 😊

man. 5. sep. 2022 00.27 skrev Abdelrhman-AK ***@***.***>:

**Comment by Abdelrhman-AK** [comment]
> **Edit, from screenshot, you're using Windows 11 which is only 64-bit..
> The bug fix I made may fix it, but I need from you to double check:
> 1) Open Control Panel > Mouse and check cursors scheme name and files of cursors
> 2) Go to C:\Users\ (username) \AppData\Local\Abdelrhman-AK\WinPaletter\Cursors
> • Replace (username) by your account/user name
> • And check if the cursors are rendered and saved or not
> 
> 

Can you do these steps ?
The next update may fix it but I need to make sure that this issue is the same as the 32-bit's

**Comment by MNSBKillJoy** [comment]
The 1. Step fixed it. Thank you!

man. 5. sep. 2022 15.08 skrev Abdelrhman-AK ***@***.***>:
