### ISSUE TITLE
Feature ideas : Command line support

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#32]
As you probably already know, Windows contains .theme files to automatically change the appearance of the system. .theme files are able to change colors (win32), mouse pointers, system sounds, wallpaper, screen saver, window metrics, visual styles from Windows XP, and accent colors from Windows Vista.
All of this still exists on Windows 10/11 (except for the windows metric which no longer works in .theme files). https://docs.microsoft.com/en-us/windows/win32/controls/themesfileformat-overview

However, some elements are not supported:
- the precise DWM\UWP accent color settings (.theme files only support settings present in the settings app)
- The visual effects settings (in particular those of the UserPreferenceMask key, such as Flat/3D menus)
- Other visual settings scattered here and there in the registry

As you can see, some of these settings are supported through WinPaletter (in addition, WinPaletter supports colorization of the mouse pointers).

So my idea is to add command line support for applying a .wpth theme (like `WinPaletter.exe apply aero.wpth`), and ideally some settings individually (however, the important thing is especially the possibility of applying a .wpth theme on the command line).

For examples, I have the Remetric/NoMeiroUI example, which contains both the ability to apply a full scheme and settings individually.
https://github.com/Tatsu-syo/ReMetrics
https://github.com/Tatsu-syo/noMeiryoUI

**Comment by Abdelrhman-AK** [comment]
That is a great idea, I'll implement it.

There is something looks like it but without using Command Prompt, open settings > Theme File management > Check: Opening the theme file applies it without opening the application.

The theme will be applied without opening app's GUI

**Comment by OrthodoxWindows** [comment]
Thanks for the information ! I didn't know about this feature.
Afterwards, the ideal would be to be able to use both options in the context menu (an "open" entry and an "edit" entry in the context menu of .wpth files). This generally uses features similar to the command line.

**Comment by Abdelrhman-AK** [comment]
I'll do this!
