### ISSUE TITLE
1-pixel glitch in Win32 previewer inactive titlebar

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#35]
![изображение](https://user-images.githubusercontent.com/1271736/188643363-25efd00a-320d-4246-b5d0-0579dcf1c185.png)
The 1-px column in the inactive titlebar in the left-hand end is painted with right-hand gradient color.

Also, the menu's lower end is 1 px shorter than the window preview behind it, it is not technically a bug but may create wrong impression of appearance so I suggest to make the "active window" preview a few pixels shorter vertically or a few pixels longer so that the border to be fully visible:
![изображение](https://user-images.githubusercontent.com/1271736/188644089-109890b2-cf1c-400d-9bbb-f12ba6263608.png)

**Comment by Abdelrhman-AK** [comment]
I have noticed the first bug a month ago and I didn't find the bug in code, but I can re-investigate about it and fix this.

In the second one, I can make Active Window Longer vertically so there won't be any confusion between Window and menu
