### ISSUE TITLE
Would not it be logical to group these two switches together?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#36]
![изображение](https://user-images.githubusercontent.com/1271736/188644927-76e3e1c1-5f58-4219-947f-bc5c0b1d83d0.png)
The "Gradient titlebar for classic apps" and "Enable flat menus" both affect the User Preference Mask registry key.

Yet, they are placed separatly and even have tifferent switch appearance ("Gradient titlebar for classic apps" has possibly not intended black background).

Would not it be more logical to place them next to each other and in the same style?

**Comment by Abdelrhman-AK** [comment]
- The dark background is a bug in the GUI theme I made for the app, I will fix it.

- My point of view was to make Gradient Titlebar toggle in its group (Of titlebars) so it will be easy for a normal user (as there may be normal users don't know UserPreferenceMask in registry). But anyway I can move this toggle to be with Flat Menus

**Comment by Anixx** [comment]
Consider other possiblilities as well:

* Moving the "flat menus" switch to the "3D objects" group

* Adding some kind of "global switches" separate group...

**Comment by Abdelrhman-AK** [comment]
I can move flat menus to 3D Objects, to follow the same logic of Titlebars

**Comment by OrthodoxWindows** [comment]
Personally, I think that the "Enable Flat Menus" parameter has no place in "3D Objects", because it activates/deactivates certain colors. I'd rather see it in the "Selection Objects" section.

**Comment by Abdelrhman-AK** [comment]
It is confusing :)
This toggle affects menu bar color and menu color, and so the hilights colors (Affects two groups)

It will be better to create a new group named User Preference Mask, including these two toggles...
