### ISSUE TITLE
The button "Make 3D looks like Windows 9x" affects only some elements

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#37]
When pressing this button only a few elements are affected while other remain colored as the current scheme, creating a mixed scheme.

изображение

Maybe this button is not necessary as there is already a set of preset schemes? Or maybe it should apply one of the preset schemes fully.

Also, since it is functionally similar to the button "Default Wondows 10/11", should not they be put together?
Or maybe just add the "Default Windows 10/11" to the list of preset schemes?

**Comment by Anixx** [comment]
Maybe just make it load the "Windows Classic (95-NT)" scheme?

**Comment by Abdelrhman-AK** [comment]
- My idea was the 3D borders only, not whole colors
- That is what I made
`btndkshadow = Color.Black ` `btnshadow = Color.FromArgb(128, 128, 128) `
` btnhilight = Color.White `
`btnlight = Color.FromArgb(192, 192, 192)` 
`btnface = Color.FromArgb(192, 192, 192)`
`BtnFrame = Color.Black`
`XenonToggle1.Checked = False '# Disable Flat Menus`

**Comment by Abdelrhman-AK** [comment]
>Also, since it is functionally similar to the button "Default Wondows 10/11", should not they be put together?
Or maybe just add the "Default Windows 10/11" to the list of preset schemes?

I can make Default Windows 10/11 a part of schemes, with name "Aero Fallback (Default Windows)"

But the button of "Make buttons 3D....." is a different idea (Not a full scheme, it is a fix for reminants as I said before)
