### ISSUE TITLE
Application keeps giving NET Framework issues with the latest version.

### ISSUE THREAD

**Issue by TF2-Gaming** [Abdelrhman-AK/WinPaletter#42]
After clean installing Windows 11 22H2 build 22622.590, and making sure all apps and frameworks are updated, when I try to launch WinPaletter, there are many NET Framework issues that occur when I use the app. This did not happen in previous versions. These issues occur when launching, when attempting to change settings, and even when closing the app.
![image](https://user-images.githubusercontent.com/112982225/189496592-dd285990-97bd-4603-8f2f-8875989a7938.png)

**Comment by Abdelrhman-AK** [comment]
Can you click on details and show me the whole details?...

**Comment by TF2-Gaming** [comment]
Hey, because the size of the details was too large for one image to cover all of it, I'll just upload the text of the details here.

>>> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinPaletter.CP..ctor(Mode Mode, String PaletteFile)
   at WinPaletter.MainFrm.MainFrm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WinPaletter
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/mundy/Downloads/WinPaletter.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Animator
    Assembly Version: 1.0.3.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/mundy/Downloads/WinPaletter.exe
----------------------------------------
ColorThief.Desktop.v46
    Assembly Version: 1.1.0.1
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/mundy/Downloads/WinPaletter.exe
----------------------------------------
Cyotek.Windows.Forms.ColorPicker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/mundy/Downloads/WinPaletter.exe
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Abdelrhman-AK** [comment]
OK. I'll work on this bug
Thank you!

**Comment by Abdelrhman-AK** [comment]
### Can you show me some registry keys? I suspect some and I want to make sure that they are the reason...
- `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent`
**I mainly suspect this key (Microsoft maybe modified number of entries of accent color array), but I want to make sure about the others as well,**

- `HKEY_CURRENT_USER\Control Panel\Colors`
- `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM`
- `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon`
- `HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Personalization`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System`
- `HKEY_LOCAL_MACHINE\Software\WinPaletter\Cursors`

**Comment by TF2-Gaming** [comment]
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***


The path HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Personalization does not exist.
The path HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System exists, but is empty.

The path HKEY_LOCAL_MACHINE\SOFTWARE\WinPaletter\Cursors does not exist.

**Comment by Abdelrhman-AK** [comment]
What about `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent` and specially the value of "AccentPalette" ?

**Comment by Yuriy-RU** [comment]
Hello!
Perhaps my problem will suggest a solution to yours.
Windows 10 Pro x64 (2009 build 19044).
![Screenshot_220911_194432](https://user-images.githubusercontent.com/113303160/189539719-31d5135d-662d-4417-b924-887bdfd23c94.jpg)
With this position in the registry, the program works fine, but as soon as I change this,
![Screenshot_220911_193952](https://user-images.githubusercontent.com/113303160/189539775-92443ca2-75d8-46ea-8e27-7c4164b64568.jpg)
I get an error when starting the program:
![Screenshot_220911_194136](https://user-images.githubusercontent.com/113303160/189539821-21c88eac-2fc3-4791-9053-2b2d1751e36d.jpg)

**Comment by Abdelrhman-AK** [comment]
That is fine.. this is a second bug with the first one.
I'll fix these and push an update today or tomorrow.

**Comment by Abdelrhman-AK** [comment]
@TF2-Gaming @Yuriy-RU 
Can you use latest version and see if there is this bug or not ?
[https://github.com/Abdelrhman-AK/WinPaletter/releases/tag/v1.0.5.1](url)

**Comment by TF2-Gaming** [comment]
The issue has been fixed, thank you!

**Comment by Abdelrhman-AK** [comment]
You're welcome!

**Comment by Yuriy-RU** [comment]
Yes, the problem with logging into the program has been solved.
But when I make any changes in Win32UI (without logging into LogonUI) after saving, the registry [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization] changes for some reason (screenshots in the previous post).

**Comment by Abdelrhman-AK** [comment]
This is extremely weird as I have tested this multiple times yesterday ...

Can you delete the wrong "PersonalColors_Background" and reuse the application and see what will happen?

**Comment by Yuriy-RU** [comment]
I am a regular user (not a programmer).
From the link in your thread found a way to make the Ctrl+Alt+Del panel black (instead of gray).
Applied reg file (Salmon_Red_Not_Theme.reg) and Ctrl+Alt+Del panel became black, also noticed that PersonalColors_Background REG_DWORD changed to PersonalColors_Background REG_SZ.
And now when I apply your program, the Ctrl+Alt+Del panel is reset to gray (PersonalColors_Background REG_DWORD).
Removed both, it (Ctrl+Alt+Del panel) always resets to gray.

**Comment by Abdelrhman-AK** [comment]
It is a mistake from me. These keys are REG_SZ and requires hash at beginning (#) and hex format..

I'll fix this issue and post an update

**Comment by Abdelrhman-AK** [comment]
@Yuriy-RU 
### I'll Delete Personal Color Background from the application as it caused bugs for Windows when it is applied correctly to registry:
1. LogonUI Screen is not changed even when the registry is modified (It is dependent on another registry key).
2. Windows Settings Bug: When you change Colors from Settings (not from WinPaletter), the colors stay unchanged, when I removed this key, Windows Settings finally could change colors

so I'll remove it from the program, but I'll keep Personal Color Accent and Background (Not the Personal one)
1. Personal Color Accent is applied correctly when you open accessibility menu in LogonUI Screen 
2. Background (Not the Personal one) is applied correctly (Screen Flicker when you log off in this color)

**Comment by Abdelrhman-AK** [comment]
@Yuriy-RU 
### I'll remove all PersonalColors_Background, PersonalColors_Accent and Background
They all caused bugs in Windows after setting them correctly, their usage is mainly for Windows 8.1, not Windows 10

**Comment by Yuriy-RU** [comment]
[Abdelrhman-AK](https://github.com/Abdelrhman-AK)
1.0.5.2
My problem solved. A great combine for "personalization". Thank you.

**Comment by Abdelrhman-AK** [comment]
You're welcome!

**Comment by TF2-Gaming** [comment]
***@***.***
