### ISSUE TITLE
What about scrollbars?

### ISSUE THREAD

**Issue by ericgl** [Abdelrhman-AK/WinPaletter#44]
Is it possible in Windows 10/11 to customize the scrollbars?
So far, I haven't been able to do so.

**Comment by Abdelrhman-AK** [comment]
No it is not possible as it is handled/rendered by visual styles not registry, unless you're forcing classic theme, then you can use WinPaletter to customize it (Classic theme only!)

Or you can download and apply custom visual styles if you want a different style to scrollbars.
