### ISSUE TITLE
WinPaletter Crashes in Windows 11 22h2

### ISSUE THREAD

**Issue by hifinerd** [Abdelrhman-AK/WinPaletter#45]
On Win11 22h2 (build 22621.521), Winpaletter will not start, regardless if I run as admin or not.
[Report.zip](https://github.com/Abdelrhman-AK/WinPaletter/files/9718601/Report.zip)

**Comment by Abdelrhman-AK** [comment]
Can you show me the details of JIT instead of Windows Error Reporting (WER)?

It looks like this:
![image](https://user-images.githubusercontent.com/59510211/194164725-836fe400-1acf-488e-aad4-73d5665ada2d.png)

**Comment by Abdelrhman-AK** [comment]
There is an issue looks like that, fixed by setting a color in Windows Settings (Not WinPaletter) and reopen WinPaletter

Issue reported #55 by @TF2-Gaming
