### ISSUE TITLE
It is possible to colorize the Taskbar without colorizing the Start Menu and the Action Center.

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#46]
Obviously, it's possible to colorize the taskbar independently of the rest by setting the "ColorPrevalence" key to 2 :

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"ColorPrevalence"=dword:00000002
```

https://www.askvg.com/tweak-colorization-settings-for-titlebar-taskbar-and-start-menu-in-windows-10/

It works on Windows 10 (except on 2015 versions). On Windows 11, it works almost safely with Windows 10 taskbar and Windows 10 start menu enabled with ExplorerPatcher. With the Windows 11 taskbar, I have absolutely no idea.

**Comment by Abdelrhman-AK** [comment]
I'll test it on both 11 and 10 and see what will happen, then I'll merge this to the application.
