### ISSUE TITLE
Windows Terminology issue with the Windows console

### ISSUE THREAD

**Issue by OrthodoxWindows** [Abdelrhman-AK/WinPaletter#47]
I just discovered the new functionality of WinPaletter, it's impressive, congratulations !

On the other hand, I have a remark to make: as indicated on the screenshot (as well as in a few other places), the PowerShell instances of the console are separate from the Command Prompt instances of the console and from the other instances of the console (External).
Yet PowerShell consoles are just instances of conhost.exe, like the Command Prompt and the externals.

I therefore propose to create a large "Console" category with three sub-categories: Command Prompt, PowerShell and Externals.

![JD7s3O5J9f](https://user-images.githubusercontent.com/100134023/194731196-1cc43d51-d58b-405b-a3c8-95171f4814c6.png)

**Comment by Abdelrhman-AK** [comment]
I'll merge them in one group "Console"
Thanks!
