### ISSUE TITLE
Desktop Blinking on Windows 10; Looks like Windows 11 22621 issue

### ISSUE THREAD

**Issue by GrosBourrin** [Abdelrhman-AK/WinPaletter#5]
hi, After resetting from the menu , my desktop blinks indefinitely, i had to reboot Windows to recover my desktop

**Comment by Abdelrhman-AK** [comment]
### It may be due to bug in auto restarting explorer after applying a color palette.
**Try to turn off auto restarting explorer from WinPaletter Settings** and then if you want to see changes, `restart explorer from Task Manager, Logging off and on, or restarting Windows`

**Comment by BigPear3465** [comment]
You need to start the application as an administrator for it to restart explorer correctly and if you happened to forget just ctrl + alt + del, open task manager and reset/exit it manually

**Comment by GrosBourrin** [comment]
that's what i done, you're probably right , i think i have run the app without admin privileges ! ty for your answer, i rerstarted windows and all is going good, ty
