### ISSUE TITLE
WinPaletter v1.0.6.1 does not start on Win 10 21H2

### ISSUE THREAD

**Issue by Yuriy-RU** [Abdelrhman-AK/WinPaletter#54]
On Win10 21h2 (2009 build 19044) Winpaletter v1.0.6.1 does not start.
The details of the JIT Debugging error are not displayed.

**Comment by Abdelrhman-AK** [comment]
I suspect an issue from two:
1) Do you use translation? As there was a bug caused this exactly, but I fixed it.

2) Which last version did work properly? 
- If it was below 1.0.5.9 then the cause may be related to the component I used to handle JSON files "Newtonsoft.JSON" to edit Windows Terminal, or related to registry... 
- I need to see if registry is intact or not (The newly related one from 1.0.5.9 and higher)
The related one `HKEY_Current_User\Console` and screenshot this and the other keys under it.

**Comment by Yuriy-RU** [comment]
Version 1.0.6 worked correctly.
![_PH_ed7fc487-6b30-4047-b756-124e14a8421a](https://user-images.githubusercontent.com/113303160/197337601-257bdb57-4b68-4985-a8fe-c3ee13dfa70e.png)

**Comment by Abdelrhman-AK** [comment]
This is a weird bug as there is no difference between 1.0.6.0 and 1.0.6.1 except slight changes that don't cause this..
Anyway, can you backup `HKEY_CURRENT_USER\Software\WinPaletter` and delete this key then try to reopen 1.0.6.1 ?

**Comment by Yuriy-RU** [comment]
Removed the HKEY_CURRENT_USER\Software\WinPaletter key and ran version 1.0.6.1.
Thank you, that helped!

**Comment by Abdelrhman-AK** [comment]
You're welcome
