### ISSUE TITLE
WinPaletter not launching on Dev 25231

### ISSUE THREAD

**Issue by TF2-Gaming** [Abdelrhman-AK/WinPaletter#55]
After I upgraded from 25227 to 25231, WinPaletter's styles were no longer working on my system. I tried relaunching the app to see if it would allow me to change the colors again, but I found the app was not able to launch itself.

**Comment by Abdelrhman-AK** [comment]
Is this issue with the latest version?

If so, try deleting registry key and reopen WinPaletter `HKEY_CURRENT_USER\Software\WinPaletter`.

If this is not working, try previous versions and tell me which one will open.

**Comment by TF2-Gaming** [comment]
The issue is happening with all versions, and it seems like the app launches but the GUI doesn’t pop up, as it shows in Task Manager as being launched, but no GUI shows on the screen.

**Comment by Abdelrhman-AK** [comment]
• Does it stay working in the background or close after seconds?

• Can you open "Event Viewer" > Windows Logs > Application and open WinPaletter, export the log and upload it here?

**Comment by TF2-Gaming** [comment]
After looking back at Task Manager, now it doesn't pop up, even after relaunch.

As for event viewer, 2 errors consistently line up next to each other.

> Application: WinPaletter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WinPaletter.My.MyApplication.MyApplication_UnhandledException(System.Object, Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.raise_UnhandledException(System.Object, Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnUnhandledException(Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   at WinPaletter.My.MyApplication.Main(System.String[])

> Faulting application name: WinPaletter.exe, version: 1.0.6.1, time stamp: 0xb52d1e5c
Faulting module name: KERNELBASE.dll, version: 10.0.25231.1000, time stamp: 0xa01ca95c
Exception code: 0xe0434352
Fault offset: 0x00149832
Faulting process id: 0x0x2210
Faulting application start time: 0x0x1D8EC6CD9094481
Faulting application path: C:\Users\mundy\Downloads\WinPaletter.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 076f13e3-2e6a-4388-93c8-152a3c7c1f56
Faulting package full name: 
Faulting package-relative application ID:

**Comment by TF2-Gaming** [comment]
There also seems to be an item I forgot to attach, as it's in Information and not Error.

> Fault bucket 2046986605132112417, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0
Problem signature:
P1: WinPaletter.exe
P2: 1.0.6.1
P3: b52d1e5c
P4: WinPaletter
P5: 1.0.6.1
P6: b52d1e5c
P7: d
P8: 6f
P9: System.NullReferenceException
P10: 
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bcbaed62-3304-4f17-adea-cc7f0094859a.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.82431310-6529-4ac7-8a31-94fbde19ba25.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220920_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6d470a8a-ac1d-4c64-a7d5-26a44d1225d8.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.70cbff90-395d-432b-8367-55fcbd085113.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.288cc4ff-89be-423a-bdf3-5ecec8d355b9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a4c138b9-5ae8-4a6e-8d55-17cab131d834.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.92ed9358-f58e-49c8-90bd-3969eac5dcad.tmp.xml
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_WinPaletter.exe_2eabb7ce8915e33a99d2fda03fb6f8b38f28bb6_5844061e_d014bac4-cf9f-4669-b64c-01dc118bc2a0
Analysis symbol: 
Rechecking for solution: 0
Report Id: 076f13e3-2e6a-4388-93c8-152a3c7c1f56
Report Status: 2147487744
Hashed bucket: 0956495b54e68d882c685b78d2e1e221
Cab Guid: 0

**Comment by Abdelrhman-AK** [comment]
• After you delete the registry, can you reopen regedit and see if the settings values are re-generated or not?

• I just want to know which stage does WinPaletter reach before this crash.

**Comment by TF2-Gaming** [comment]
Where are the settings values exactly?

**Comment by Abdelrhman-AK** [comment]
Any key under:
`HKEY_CURRENT_USER\Software\WinPaletter`

Especially 'Settings'

**Comment by TF2-Gaming** [comment]
Ok uhm, crazy thing just happened.
Apparently, the issue resolved itself by me setting an accent color in settings, deleting the registry key, and then reopening the app. I wonder if the app checks for an accent color, and when it doesn't find one it crashes.

**Comment by Abdelrhman-AK** [comment]
This is crazy and weird to be honest 😂
WinPaletter doesn't check for a scheme, Briefly, the only things that WinPaletter does are the following:

1) Associate theme and settings file and load the translation. 

2) Detecting the Current OS to read the registry correctly. 

3) Get The applied wallpaper to make it visible in the preview.

4) Check for license agreement.

5) if it is the first time you open a version, it will show you what's new in a form. 

6) Check if the user opened a theme file or directly.

7) If it is a theme file it will load it only.

8) If directly, WinPaletter will read the registry and write values to variables, and a second palette will be loaded in the background/memory which is the default Windows and which is applicable when you press the undo button or right click and press on Default Windows

**Note: the default scheme is pre-written in the code and not loaded from the registry. 
---

I can investigate more about this weird bug and rewrite some lines in application startup code, and post an update when I have some free time cause I'm busy these days.
