### ISSUE TITLE
ctd after changing lang to russian

### ISSUE THREAD

**Issue by porkmanager** [Abdelrhman-AK/WinPaletter#56]
• Date of report: 13 ноября 2022 г. - 21:19:21
• OS: Майкрософт Windows 11 Корпоративная - 10.0.22623.885 - 64-bit
• WinPaletter Version: 1.0.6.2
--------

• Error Message:
   Ссылка на объект не указывает на экземпляр объекта.

• Stack Trace:
   в WinPaletter.Localizer.Populate(List`1 PopCtrlList, Form Form)
   в WinPaletter.Localizer.LoadLanguageFromFile(String File, Form _Form)
   в WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   в Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   в Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by Abdelrhman-AK** [comment]
- I will fix this
- Does this happen in WinPaletter 1.0.6.1 or the app doesn't start completely ? 
- Temporary Fix: You can delete or move the translation file, it will open normally

**Comment by Abdelrhman-AK** [comment]
Can you use now [Version 1.0.6.3](https://github.com/Abdelrhman-AK/WinPaletter/releases/tag/v1.0.6.3) with the [modified russian language](https://github.com/Abdelrhman-AK/WinPaletter/blob/master/Languages/Russian%20-%20by%20AndreiKopishev.wplng) as the old file had issues too with the app.
