### ISSUE TITLE
Error message while applying the theme

### ISSUE THREAD

**Issue by boromyr** [Abdelrhman-AK/WinPaletter#59]
I get this error message when applying WinPaletter changes:
![image](https://user-images.githubusercontent.com/52782032/207142178-6e197d12-6af0-4c23-8a44-e7bfaa927de3.png)
note that the only change made through the app compared to the Windows settings is the color of the status bar.

Windows 11 22H2 stable
Skin: [bliss OS](https://www.deviantart.com/niivu/art/bliss-OS-for-Windows-11-22H2-925306617)
Skin mod: [SecureUXTheme](https://github.com/namazso/SecureUxTheme)
WinPaletter 1.0.6.3

Files
[colors settings.zip](https://github.com/Abdelrhman-AK/WinPaletter/files/10211632/colors.settings.zip)

**Comment by Abdelrhman-AK** [comment]
- Does this happen when you run WinPaletter as administrator or not?
- Does this happen with the native (original) theme?

**Comment by Abdelrhman-AK** [comment]
### It seems that you are trying to apply transparent colors (Which isn't supported). 
### Try again: Open Windows Settings, Personalization and choose any color, reopen WinPaletter (as administrator will be better) and then change colors
![bug](https://user-images.githubusercontent.com/59510211/207557581-5ef4bd68-4e15-4e07-8723-b33897723810.png)

**Comment by Abdelrhman-AK** [comment]
I'm sorry for late response, I had network troubles.

- Try to Re-open WinPaletter as administrator and try again.
- If you enabled a toggle of any feature (Cursors/Terminals) try to disable them (one by one) and see which one will be the cause of this error. 
- Using a custom mod/theme/visual doesn't guarantee that colors will be applied as it should.

**Comment by EldritchEevee** [comment]
**This app is not supported on Windows 11 due to back-end changes.** While it may work, a LOT of features aren't compatible.

Interested in customizing your System? Downgrade to Windows 10.
