### ISSUE TITLE
Why shouldn't WinPaletter be used on 22621 yet?

### ISSUE THREAD

**Issue by Skyyblaze** [Abdelrhman-AK/WinPaletter#6]
I saw the warning but what are the issues?

**Comment by hedhehd** [comment]
It broke the explorer.exe. And that's a critital Windows file. But I repaired it with sfc /scannow in cmd. But it DID work. Only just broke the file.

**Comment by Abdelrhman-AK** [comment]
It broke Windows Apps/Explorer for users on this build
Issue Link: https://github.com/Abdelrhman-AK/WinPaletter/issues/3

You can Fix with sfc/scannow if you faced this bug

**Comment by Skyyblaze** [comment]
I see interesting, but that issue makes me believe it's fine to use aslong as I don't touch the "Blur" option?

**Comment by Abdelrhman-AK** [comment]
### Issue has been known:
Automatic Restarting Explorer after applying palette crashes the explorer...
Now you can use WinPaletter in Windows 11 22621, but with disabling auto restart explorer from settings.. to see instant effects, restart explorer by yourself, not by the program.

![Untitled](https://user-images.githubusercontent.com/59510211/173231094-68fb41c7-c21e-4d6d-bff0-ea19ed338829.png)

**Comment by Skyyblaze** [comment]
Alright I see, thanks!
