### ISSUE TITLE
Windows 7 behavior 

### ISSUE THREAD

**Issue by stanleeway** [Abdelrhman-AK/WinPaletter#60]
i want Windows settings background to remain white with only Apps background changing to black ,is that possible ?

![Untitled 2](https://user-images.githubusercontent.com/58675554/210025612-b831551b-e70e-4be5-b053-ed2c560df539.jpg)
![Untitled 4](https://user-images.githubusercontent.com/58675554/210025617-d53889ac-5e09-4cc5-b2f8-b8284e76c0ee.jpg)

**Comment by Abdelrhman-AK** [comment]
It is not possible, Microsoft made Dark/Light Mode with two options only: one for all apps `(Apps Mode)` and the other for Windows elements like taskbar, start, action center, ... `(Windows Mode)`

**Comment by stanleeway** [comment]
i figured, at least it manages to force a different Settings Icons color than the theme color & so much more which is great , amazing app by the way,keep it up

**Comment by Abdelrhman-AK** [comment]
Thanks!
