### ISSUE TITLE
Choosing Windows Classic theme in Windows 7 does not show it in preview.

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#62]
![изображение](https://user-images.githubusercontent.com/1271736/215258576-4475be55-ac9e-4d40-bf1f-5ef9cf2a295f.png)

Here the Windows Classic is chosen but the preview is not Windows Classic.

Also, I suggest to implement Windows Classic as a separate mode (along with Windows 8.1, etc) because its settings are common for all windows versions.

**Comment by Abdelrhman-AK** [comment]
> Here the Windows Classic is chosen but the preview is not Windows Classic.
I can implement a classic preview here.

> Also, I suggest to implement Windows Classic as a separate mode (along with Windows 8.1, etc) because its settings are common for all windows versions.
It is already separate. Win32UI is the way to customize the classic colors
