### ISSUE TITLE
Window Metrics and fonts in Windows Classic (Win32) mode include much more parameters than currently implemented

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#63]
For instance, Window Metrics allows to make the window caption buttons rectangular in Windows Classic mode.

**Comment by Abdelrhman-AK** [comment]
Can you show me screenshot, documentation or registry entries so I can understand this and implement it?

**Comment by Anixx** [comment]
http://systemmanager.ru/win2k_regestry.en/58584.htm

http://systemmanager.ru/win2k_regestry.en/58842.htm

**Comment by Abdelrhman-AK** [comment]
It is already implemented, may be their names didn't describe them properly.

![Screenshot_20230128-191343_GitHub.png](https://user-images.githubusercontent.com/59510211/215279798-3e1452dd-839e-471f-9756-0be75b2a16a1.png)

**Comment by Anixx** [comment]
Moving those sliders does not change the preview. They affect only Windows Classic theme.

**Comment by Anixx** [comment]
Maybe implement in Metrics&Fonts also a classic theme preview?

**Comment by Anixx** [comment]
Also, I suggest to change the name of Win32 button to "Unthemed" or "Classic" because, themed apps are also Win32.

**Comment by Abdelrhman-AK** [comment]
> Moving those sliders does not change the preview. They affect only Windows Classic theme.

When I tested it at first, it didn't change the modern ones, it only changed the classic ones.

I'll give it a second try and see if it changes the modern or not.

**Comment by Abdelrhman-AK** [comment]
> Maybe implement in Metrics&Fonts also a classic theme preview?

I'll try to make all previews in metrics and fonts in classic

**Comment by Abdelrhman-AK** [comment]
> Also, I suggest to change the name of Win32 button to "Unthemed" or "Classic" because, themed apps are also Win32.

I'll change its name into "Classic" because of the same purpose you said, there are shared items between modern and classic.

**Comment by Anixx** [comment]
"Modern" is UWP apps theme and what we see in the previews are better described as "Themed" or "Aero". Windows Metrics I think, do not affect the themed buttons.

**Comment by Abdelrhman-AK** [comment]
> Windows Metrics I think, do not affect the themed buttons.

Yup, you're right. The only buttons that can be configured are the buttons of titlebar (Close, Minimize, Maximize) with a Classic theme is enabled.
