### ISSUE TITLE
Preview in Windows 7 mode is empty after returning from the Metrics window

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#65]
![изображение](https://user-images.githubusercontent.com/1271736/215283559-e10368f5-a996-480c-b111-c31b9c6486ed.png)

This happens for all chosen themes.

**Comment by Abdelrhman-AK** [comment]
There is a remnant from old code I forgot to remove, when the classic theme is chosen it make the preview all empty.

I'll fix this by the classic preview being implemented in the main form.

**Comment by Anixx** [comment]
Don't you think it would be better to make the buttons in the bottom tabs intead of separate dialog windows?

**Comment by Abdelrhman-AK** [comment]
I really thought about this idea months ago, I tried it and found the code will be messy and I was confused then. Creating them separately in forms/dialogs was easier to me.

I might give this a try in the future.

**Comment by Anixx** [comment]
It was easy when I was at school and we used VB6.

**Comment by Abdelrhman-AK** [comment]
Yes it is easy, my problem is the amount of code and amount of controls on the form. 

Main Form is already lagging with me (Other forms are fine) during design mode. It has invisible tabs (TablessControl) containing many controls (For Windows 11, 10, 8.1, 7 & Logs).

Imagine adding dozens of other controls from other forms/dialogs, it will make designing mode unbearable to me.

When I finish more features and fix the current bugs, I may give it a try.
