### ISSUE TITLE
Problem GUI

### ISSUE THREAD

**Issue by Stoffelchen** [Abdelrhman-AK/WinPaletter#70]
Hello,
with the current version there seems to be a display problem --> screenshot. The previous version worked flawlessly.

Greetings
Stephan
![Screenshot 2023-02-13 165827](https://user-images.githubusercontent.com/108582797/218508217-7ad69341-2fb7-461f-89a8-3b677901aad9.png)

**Comment by Abdelrhman-AK** [comment]
I have changed settings of DPI in the manifest file. I'll undo this and post an update soon.

**Comment by Abdelrhman-AK** [comment]
### Undoing this code didn't fix the problem of DPI. You can fix it manually until I make the application handle DPI settings better:

![image](https://user-images.githubusercontent.com/59510211/218558372-aa3de6d9-7f2f-44d5-a400-b3776256b58b.png)
