### ISSUE TITLE
Application goes not responding

### ISSUE THREAD

**Issue by ThrnSC87** [Abdelrhman-AK/WinPaletter#74]
Application goes not responding on windows 10 22h2 when it gets to applying windows metrics and fonts and no clue why since on windows 11 works normally.

**Comment by Abdelrhman-AK** [comment]
- Try again with running it as administrator.
- Wait for a minute or two if it freezes.
- If not responding at all try WinPaletter 1.0.6.9


- Anyway I'm testing it now on Windows 10 22H2 and there is no problem with me

**Comment by ejrv** [comment]
> * Try again with running it as administrator.
> 
>     * Wait for a minute or two if it freezes.
> 
>     * If not responding at all try WinPaletter 1.0.6.9
> 
> 
> Anyway I'm testing it now on Windows 10 22H2 and there is no problem with me

if these all didnt work, backup, and install an older windows

**Comment by HongYue1** [comment]
Same here, 22H2, and it's not responding for a long time, also it messes up the dpi and makes text bigger.

![image](https://user-images.githubusercontent.com/87040288/222968825-033965fe-eba4-41e8-87b7-162325e59a91.png)

![image](https://user-images.githubusercontent.com/87040288/222968831-bffa715c-a9c9-463e-9ffc-f231bb00b90d.png)

![image](https://user-images.githubusercontent.com/87040288/222968761-afa72c78-33f0-46fa-977b-282e2f1c9f8d.png)

**Comment by HongYue1** [comment]
@ThrnSC87  are you using ExplorerPatcher too?

**Comment by Abdelrhman-AK** [comment]
> Same here, 22H2, and it's not responding for a long time, also it messes up the dpi and makes text bigger.
> 
> The only thing I did was to change "Title bar" color.
> 
> Edit: WinPaletter 1.0.6.9 also don't respond on applying, but it doesn't mess up the DPI/font.
> 
> 
> ![image](https://user-images.githubusercontent.com/87040288/222968825-033965fe-eba4-41e8-87b7-162325e59a91.png)
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/87040288/222968831-bffa715c-a9c9-463e-9ffc-f231bb00b90d.png)
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/87040288/222968761-afa72c78-33f0-46fa-977b-282e2f1c9f8d.png)
> 

You can solve this by these steps:
- Logoff and Logon, you will find text sizes are returned to their defaults
- Open WinPaletter and open Metrics
- Uncheck the toggle in the upper part of the form
- Load and apply

**Comment by Abdelrhman-AK** [comment]
- Nothing changed in the mechanism of Metrics, it is the same in 1.0.6.9 and 1.0.7.x

- You can uncheck Metrics' toggle and see if it freezes or not.

**Comment by HongYue1** [comment]
Ok, now it suddenly works but the dpi is big and I can't revert it back

**Comment by Abdelrhman-AK** [comment]
Here you are another solution worked for another person:
https://github.com/Abdelrhman-AK/WinPaletter/issues/76#issuecomment-1433582748

**Comment by HongYue1** [comment]
> Here you are another solution worked for another person: [#76 (comment)](https://github.com/Abdelrhman-AK/WinPaletter/issues/76#issuecomment-1433582748)

This solution works, thanks for your help!!

**Comment by Abdelrhman-AK** [comment]
You're welcome!

**Comment by HongYue1** [comment]
> You're welcome!

By the way, would it be possible to add an option to remove text from the Title Bar, please?

**Comment by Abdelrhman-AK** [comment]
### I tried two methods:
1) I have an empty ttf font, used it in Metrics & Fonts and did a logoff and logon. but it is buggy here:

![Untitled1](https://user-images.githubusercontent.com/59510211/222980726-da1992f4-5936-4998-95d8-d201d1fdede7.png)

2) I tried to set Titlebar font size to `1` and did a logoff and logon and this is the result:

![Untitled0](https://user-images.githubusercontent.com/59510211/222980769-6154ce64-ccc6-46db-b3d4-b98062388002.png)

### Conclusion: 
It is not perfectly done by registry modification, you can search online for custom visual styles but may not have luck finding your option as I have never seen it before.

**Comment by HongYue1** [comment]
I have an Idea, what about setting the Title Bar text color to that of the title bar?

**Comment by Abdelrhman-AK** [comment]
There is an option in "Classic Colors > Titlebars" but it won't be effective. It is used for classic themes. The modern theme depends on the visual styles not registry, so it is not effective.

**Comment by HongYue1** [comment]
> There is an option in "Classic Colors > Titlebars" but it won't be effective. It is used for classic themes. The modern theme depends on the visual styles not registry, so it is not effective.

I also can't seem to find any solution on Google, it seems like we are stuck with it, sadly.

**Comment by Abdelrhman-AK** [comment]
You're welcome :)
