### ISSUE TITLE
Change window background color

### ISSUE THREAD

**Issue by Cheshire-Behemoth** [Abdelrhman-AK/WinPaletter#75]
I would like to be able to change the background of the working window. By default in the system, it is either white or dark. A great feature would be to change these colors arbitrarily at the request of the user.

**Comment by Abdelrhman-AK** [comment]
I'm sorry. It is not possible to modify it perfectly by Windows Registry.
Go to `Classic Colors (formerly Win32UI) > 3D Objects > Face` and change the color

This is the imperfect look after modifying:
![Screenshot 2023-02-14 155510](https://user-images.githubusercontent.com/59510211/218758604-1c0b193a-1347-43bf-a86b-71429b0801de.png)

### If you want a consistent\perfect look, use a custom Visual Styles
