### ISSUE TITLE
Implement switch for icon shadows in the icons properties dialog?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#80]
I suggest to implement the switch for icon shadows in the icons properties dialog.

Also consider implementing switches for windows shadows and solid selection rectangle in Explorer (as opposed to dotted contour).

**Comment by Abdelrhman-AK** [comment]
I have implemented Shadow for Window Borders and it will come soon (A part of ane coming feature; Windows Effects)

> I suggest to implement the switch for icon shadows in the icons properties dialog.
> 
> Also consider implementing switches for solid selection rectangle in Explorer (as opposed to dotted contour).


If you have documentations for both or registry entries, I will implement these items in Windows Effects
