### ISSUE TITLE
Something is wrong with the Windows XP preview

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#89]
![изображение](https://user-images.githubusercontent.com/1271736/222267854-af505edb-7278-4bb4-8fa3-c642331d24e7.png)

What these "Apps" are meant to be? Win32 or Metro (there is no Metro in WinXP)? Anyway, they have no window border.

The taskbar is also not visible.

**Comment by Abdelrhman-AK** [comment]
It is a bug in the component I used to get bitmaps from msstyles.

Try to change the theme and see if it will be correct or not

**Comment by Anixx** [comment]
Somehow it does not appear in the Win2000 default color scheme. The reg file for my theme where the bug appears is attached.

[Anixx - WinterTree.zip](https://github.com/Abdelrhman-AK/WinPaletter/files/10865500/Anixx.-.WinterTree.zip)

**Comment by Anixx** [comment]
%localappdada%\Abdelrhman-AK\WinPaletter\VisualStyles\Luna - there is no such directory.

**Comment by Abdelrhman-AK** [comment]
- I have just remembered, you are using a classic theme in Windows 10.

- There are limitations in the component I used "Advanced UX theme wrapper". It can't process a visual styles file when classic mode is enabled. If a classic theme is enabled it will give exception errors saying that visual styles are disabled and so there is the problem.

**Comment by Abdelrhman-AK** [comment]
> %localappdada%\Abdelrhman-AK\WinPaletter\VisualStyles\Luna - there is no such directory.

I have corrected the path

**Comment by Anixx** [comment]
When using other color scemes, there is no such issue.

**Comment by Anixx** [comment]
This path also does not work.

**Comment by Abdelrhman-AK** [comment]
> When using other color scemes, there is no such issue.

With classic theme ?
As it didn't work with me at all with a classic theme enabled in Windows XP

**Comment by Anixx** [comment]
In Windows 2000 default scheme all is OK, no error:
![изображение](https://user-images.githubusercontent.com/1271736/222270858-f33b6604-4e37-4416-bcc4-a971e03cd791.png)

**Comment by Abdelrhman-AK** [comment]
> This path also does not work.

`%localappdata%\Abdelrhman-AK\WinPaletter`

**Comment by Anixx** [comment]
"C:\Users\User\AppData\Local\Abdelrhman-AK\WinPaletter\VisualStyles\Luna"

![изображение](https://user-images.githubusercontent.com/1271736/222271236-7e6542af-d0d2-45cb-9da0-cf02029a54c8.png)

**Comment by Anixx** [comment]
I was wrong in my previous comments, this issue appears in all color schemes.

**Comment by Abdelrhman-AK** [comment]
Then it is due to the problem of the component.

I can't fix it. But I can implement an alert that appears when a classic theme is applied.
