### ISSUE TITLE
Gray UAC "Show More Details" text after changing colors

### ISSUE THREAD

**Issue by hifinerd** [Abdelrhman-AK/WinPaletter#9]
See title. This appears to occur with any palette change I've attached my .wpth file.
[https://drive.google.com/file/d/1DI6BWsl4ld12lSMNFm98xXWLeBcEWf-v/view?usp=sharing](https://drive.google.com/file/d/1DI6BWsl4ld12lSMNFm98xXWLeBcEWf-v/view?usp=sharing)
Edit: For some reason, the UAC text and the volume slider color are both determined by the active titlebar color. Please make this more clear.

**Comment by Abdelrhman-AK** [comment]
Windows makes these items have the same color, I'll add a note beside active titlebar color to make this clear.
