### ISSUE TITLE
The selected task button in Windows XP Classic theme should have checkers pattern.

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#90]
![изображение](https://user-images.githubusercontent.com/1271736/222268363-b587f10b-2fd0-46ac-ab4a-1eef6b186ae8.png)

Should be:
![изображение](https://user-images.githubusercontent.com/1271736/222268533-9bcd6d46-77aa-4fc1-9d9f-17996dd435cf.png)

**Comment by Abdelrhman-AK** [comment]
I'll fix this
