### ISSUE TITLE
Adding accessibility features?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#92]
The accessibility page in Settings app has several options, related to visual effects, mouse and text cursors, daltonism filters, etc.

![изображение](https://user-images.githubusercontent.com/1271736/222274253-628196c6-5e2c-4bdf-b732-762b36510592.png)

![изображение](https://user-images.githubusercontent.com/1271736/222274572-0e0f1976-9a57-4298-87b9-1cf9f3c9dafc.png)

**Comment by Abdelrhman-AK** [comment]
Currently I don't know their registry keys. I'll search about them and when I know their keys, I'll implement them.

If you already know some, please write them down.

**Comment by Abdelrhman-AK** [comment]
I won't be able to do them.
I managed to know their registry keys, but setting a custom color to cursor is not affected at all. It is managed by a system function\API that I don't know.

I won't implement Accessibility now, maybe in the future.
