### ISSUE TITLE
Aero fallback scheme name

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#93]
![изображение](https://user-images.githubusercontent.com/1271736/222276691-abd91748-2bbe-4253-8e65-299973399108.png)

Should it not be better named "Aero Fallback (default Windows 7-11)? I mean "Default Windows" is usually associated with the Win 2000-XP scheme.

**Comment by Abdelrhman-AK** [comment]
Aero is known from Windows Vista till now and still used in classic colors.
I can rename it to Aero Fallback (Default Windows Vista-11)
