### ISSUE TITLE
Description is unclear in Windows Metrics

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#95]
I think, these mean button sizes? Otherwise what is "titlebar width"? The labels are unclear.

![изображение](https://user-images.githubusercontent.com/1271736/222279095-c629a0ef-5afd-491f-99f8-eabaebc0654b.png)

**Comment by Abdelrhman-AK** [comment]
I just copied them as the same as registry. I can rename "Width" to "Classic Button Width"
