### ISSUE TITLE
There is no option fo raster fonts in Console settings

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#96]
Cannot set like this in WinPaletter:

![изображение](https://user-images.githubusercontent.com/1271736/222282590-7412c717-5994-4f86-a7a8-2b149d77865b.png)

**Comment by Anixx** [comment]
Also, the changing the font does not affect the preview:
![изображение](https://user-images.githubusercontent.com/1271736/222283427-eba0357b-69c4-4b2c-9cca-44651c876457.png)

Also, there is no 6x9 size, instead there is 6x8.

**Comment by Abdelrhman-AK** [comment]
Uncheck raster fonts and it will change fonts previews.

**Comment by Abdelrhman-AK** [comment]
And I don't see here 6x9 option. maybe it is related to the Russian language layout or something else
![Untitled0](https://user-images.githubusercontent.com/59510211/222287638-afe7cd10-94d8-413d-9056-280d07253ac2.png)

**Comment by Anixx** [comment]
If "raster font" is checked, the font choice possibly should be disabled?

**Comment by Anixx** [comment]
Also, there is no 8x9.

**Comment by Abdelrhman-AK** [comment]
> If "raster font" is checked, the font choice (and weight) possibly should be disabled?

I'll try to do this

**Comment by Abdelrhman-AK** [comment]
> Also, there is no 8x9.

I won't be able to create a preview from 8x9 as I don't have it. I take screenshots from it and remove the background to create a preview.

**Comment by Anixx** [comment]
Forme it isactually the same font as 8x8 in your system...

**Comment by Abdelrhman-AK** [comment]
I'll make 6x9, 8x9 options but with previews 6x8, 8x8
