### ISSUE TITLE
What is this switch for in Cursors tab?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#97]
It is unclear.
![изображение](https://user-images.githubusercontent.com/1271736/222285730-53a8b8b2-785a-4b82-b61f-051fdaafece8.png)

**Comment by Abdelrhman-AK** [comment]
It is considered as a lock, if enabled it will apply the cursors everytime you apply a theme. If disabled it won't apply

**Comment by Anixx** [comment]
The indicator to the left of the switch is always green, regardless of the switch state.

**Comment by Abdelrhman-AK** [comment]
It is a static image

**Comment by Abdelrhman-AK** [comment]
I'll make the toggles with two images.
