### ISSUE TITLE
Looks like a typo in the scheme name

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#98]
![изображение](https://user-images.githubusercontent.com/1271736/222971479-358f77cb-2991-4a68-89ba-788ef7d8ca00.png)

I mean the colon.

Also, I suggest to make the description shorter: "Aero Fallback (Vista-11)" to make similar to other theme names and avoid confusion with the default classic theme colors under Vista and Win7.

**Comment by Abdelrhman-AK** [comment]
I intentionality made the colon as they are range, starting from Vista and ending in 11.

I can do your recommendation anyway.
