### ISSUE TITLE
The arrow lines are barely visible

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#99]
![изображение](https://user-images.githubusercontent.com/1271736/222971817-c5d2df72-ff00-415d-9ea2-2a0fdcbe1199.png)

Here, the lines pointing to the elements of interface are light grey, which makes them barely visible. Would it be better to use some less common and more contrastive color?

**Comment by Abdelrhman-AK** [comment]
I will make the line dark gray in Light mode, and vice versa with dark mode.
